### ISSUE TITLE
Problem with Webminstats

### ISSUE THREAD

**Issue by Feliksas** [webmin/authentic-theme#1]
Greetings,
There's a problem with displaying Webminstats panorama, while this theme is active.
Should be: 
http://3.bp.blogspot.com/-KHEcs0TlcIE/U_pUN44P0yI/AAAAAAAAULM/sFXVnMev2So/s1600/Screen%2BShot%2B2014-08-24%2Bat%2B22.06.18.png

Actual situation:
https://yadi.sk/i/S1x1sKBebiTVz

This module is 3rd-party, but can be installed from within Webmin itself (Webmin Modules/Install/Third party module from: "webminstat")

**Comment by qooob** [comment]
Added basic support for this module. Will be supported in _Authentic Theme_ v.7.1.0.

**Comment by gerbier** [comment]
I am the author of webminstats module. I am using the icons_table call (from core api)  to display aligned graphs, what's wrong with this ? (I had a look at others modules, and it seems to common).
Can you provide a documentation link ?

**Comment by qooob** [comment]
Hello! Thanks for contacting.

I'm not using the part of the code that generates icons. But in the recent version I have made a work around for your module.

You can see the way theme works by simply installing it and looking at `authentic.pl`.

**Comment by gerbier** [comment]
Hello,

Yes, I can install it on an ubuntu 14.10.
And yesterday, I had a look at ui-lib (which does not exists when webminstats was first coded) :
in next release, I will try to replace my code by ui_* functions. It should work better with themes.

----- Mail original -----

**Comment by qooob** [comment]
Great, thanks!

**Comment by gerbier** [comment]
Hello

I just release today a new version of webminstats (2.11) which works well with authentic theme, without any workaround in your code.
You will be able to remove this code when you want.

regards, 


----- Mail original -----

**Comment by qooob** [comment]
Perfect, I'll check, thanks, pal!

**Comment by qooob** [comment]
@gerbier Please take a look: https://github.com/qooob/authentic-theme/issues/889#issuecomment-344231643
