### ISSUE TITLE
Desktop notifications: close on click

### ISSUE THREAD

**Issue by lunarovic** [webmin/authentic-theme#1132]
I see you recently added the functionality to be able to click on the desktop notification and it will take me to the same place as if I clicked on the sidebar notification, which I really like. I actually already wanted to make an issue for that, but you beat me to it. 🙂

And now I think only one little thing is missing: when you click on the desktop notification to take you somewhere, it should also close, not remain sitting there, because you obviously don't need it anymore. Closing the desktop notification on click is a normal and expected behavior on other websites where I use the desktop notification feature.

<hr>

Another related thing I wanted to ask. I just got a notification about a new Authentic theme version (19.15). I click on the desktop notification, but it just refreshes the page because I'm already on the System information page. I then tried the sidebar notification and it does the same thing. I understand that's expected behavior because the button for updating the theme is on that page, so it takes me there correctly, but why not initiate the update on notification click? Although that is maybe a bad idea because it's probably not good to do things without confirmation. And yes, I know about the little green update button embedded in the sidebar notification. I also noticed that if I click the normal part of the notification, that little green button will disappear.

**Comment by qooob** [comment]
Hi,

Great analysis, thank you.

I expected notifications to be closed. I will double check tomorrow.
