### ISSUE TITLE
Mail: Display previous/next buttons at the end of the emails list as well

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1189]
When reading email i have `< and >` to read previous and next email but those are only at the top. When you are finish reading you have to scroll to the top to go to the next/previous email and therefore it would be nice if there was the same at the end of the emails.

**Comment by rostovtsev** [comment]
Hi, Sopor!

It sounds like a good idea. I think that extra navigation should only appear when the list of messages extra long. We could detach controls from the top and attach them to the bottom when user scrolls down enough. 

I believe there should be no top and bottom controls visible at the same time.

I will try adding this on the next beta.

**Comment by iliajie** [comment]
I think, this is the feature we no longer want. Also, no other mail services duplicate controls at both top and bottom.

Nowadays, the best is to automatically control the height of the container for mail, similarly Google Mail does.
