### ISSUE TITLE
bookmark star disappear

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1211]
If i have bookmarked `https://192.168.0.12:10000/nginx/?xnavigation=1` i have a yellow star on the page (in this case the nginx), but if i open one of my sites and then press the `Return to server listing` the yellow star is now gone. I can see the URL is not the same. It now looks like this `https://192.168.0.12:10000/nginx/index.cgi?xnavigation=1`.

**Comment by rostovtsev** [comment]
Yes, that kinda an issue. I'll see what I can do.

Thank you!
