### ISSUE TITLE
Issue with File ALCs module

### ISSUE THREAD

**Issue by qwrty-ftw** [webmin/authentic-theme#1229]
Hello,

I'm wondering if someone else have got same issue with the webmin File ACLs module and authentic theme.

(https://sourceforge.net/projects/webmin-fsacls/)

I can add user or group, but i can't set right even if i mark RWX and I applied from module.

eg: want to add right RWX to user test1 on folder /tmp => user is add, but no right are set.
(if I do manually: setfacl -m u:test1:rwx /tmp => works great)

Anyone got the same issue with the module and authentic theme ?
Or it's a module side issue ?

It work great before, and i can't remember when it stop to work.

Thanks you.

**Comment by rostovtsev** [comment]
Hi,

How does it work if you switched to an old theme?

**Comment by ochbob** [comment]
I tried to switch, but i stay on authentic theme :/
last time i broke my authentic theme, so I edit some file to set root theme the old one, and uninstall authentic theme to reinstall non beta theme (I forgot to update webmin to 1.894.1031.0633)

But i cant remember the part I change in webmin config file to allow the rollback.

Can you help me on this point, so i could try old theme ? =3

**Comment by rostovtsev** [comment]
Do _Webmin/Change Language and Theme_ module.

**Comment by ochbob** [comment]
OK, thank you, it works :)

On OLD theme, all works good.

 So it's authentic theme side issue.

If you want some tests, just tell me :)

**Comment by rostovtsev** [comment]
I see now. The module's developer should fix this bug. It's not Authentic Theme issue. There is incompatibility issue, which should be addressed by the module itself. Module was updated over 4 years ago.

Please contact module developer for this issue to be fixed.

**Comment by ochbob** [comment]
I do not understand, with old webmin theme it works great ?

So it cant be a module issue right ?

**Comment by rostovtsev** [comment]
There are incompatibility issues. Many old modules had to be fixed to work right.

If a module developer doesn't strictly follow all rules, things will/would fail with new theme. Old themes are not SPA (Single Page Application.)

**Comment by ochbob** [comment]
Ok, I see now, thank you.
I will try to contact the admin of module, and pray for an answer :D

**Comment by rostovtsev** [comment]
File ACLs should be added to File Manager in the future. I'll take a look

**Comment by ochbob** [comment]
Oh, this will be great !

Admin of module, is an french teacher now retired, so I think we will never get a module update :/
(anyway, I tried to contact him with the only one email adress we get, will see...)

**Comment by rostovtsev** [comment]
I find this to be a good feature to reside under File Manager.

**Comment by ochbob** [comment]
Completely agree, it would be really great :D

**Comment by qwrty-ftw** [comment]
Hello @iliajie hope you are doing well.
I'm wondering if there is any news about this feature integration into the file manager ?

If not, do you think it will be easy to fix the old module or it need a full rewrite ? :(
I'm not familiar at all with perl, but if it's not complicated, I can try to fix it if it's not a big change.

**Comment by iliajie** [comment]
There is a way to view ACLs already by enabling it in Module Preferences page. Although, editing ACLs hasn't been implemented yet.

**Comment by qwrty-ftw** [comment]
Yes, I'm just looking for this feature, I saw the view of ACL, which is already awesome :D

**Comment by iliajie** [comment]
Great! Well, if there is a demand for this feature I will be able to add it then!

If it's not big of a deal for you to share, may I ask what is the most common commands (flags) that you use to set ACLs?

**Comment by qwrty-ftw** [comment]
-m to add specific ACLs  + -R  to add recursivity =>` setfacl -m g:demo:rw -R directory` or for example `setfacl -m u:demo:rw file`
-b to delete all ACLs => `setfacl -b file`
-x to delete specific ACLs => `setfacl -x g:demo file` or s`etfacl -x u:demo file`

That's globally this one I use regularly.

**Comment by iliajie** [comment]
> -m to add specific ACLs + -R to add recursivity =>` setfacl -m g:demo:rw -R directory` or for example `setfacl -m u:demo:rw file`
> -b to delete all ACLs => `setfacl -b file`
> -x to delete specific ACLs => `setfacl -x g:demo file` or `setfacl -x u:demo file`

The work on `setfacl` support was started here https://github.com/webmin/webmin/pull/1846.

**Comment by qwrty-ftw** [comment]
Nice !
Thank you. I will do some test.

**Comment by iliajie** [comment]
Webmin 2.020 has it all. Upgrade, don't apply the patch.

**Comment by iliajie** [comment]
ACLs support in File Manager is fully implemented by now.
