### ISSUE TITLE
Theme: Navigation menu with icon driven UI (for users)

### ISSUE THREAD

**Issue by iliajie** [webmin/authentic-theme#1401]
Hi there @iliajie 

First post here - so, first of all - big handshake and wave at you for all your hard work - many thanks and good karma issued in your direction :-)

Next - I am a newbie with webmin/virtualmin, so excuse me if I am not completely accurate about such terminology and such.... but I do want to contribute to the awesomeness that's already been created....

So - with all the positive things said, please allow me to express my wonder at how I have experienced the Usermin and Virtualmin aspects....

I do wish for a simpler interface in Virtualmin.  The Webmin side is really fine for sys-admins (although could do with some re-organisation of placements!).  But Virtualmin is really a bit confusing and not very intuitive for "end-user" (e.g. a web hosting customer) - particularly those coming from cpanel with its polished Graphical User Interface.

I can see from above comment @TomasHurtz mentions icon file and I think the point would be to make a more icon realized dashboard - perhaps taking into consideration to the top most features that a typical end-user is likely to want.

For example, when end-user log into cpanel user account, you have the icons UI laid out nicely in front of you and it's very intuitive to know where to click for the function you need.  e.g. file manager, database manager, email accounts .  [Example image: ](https://hostingfacts.com/wp-content/uploads/2019/05/cPanel-dashboard.jpg)

I guess you can say the same thing for CentosWebPanel or CWP :  [Example image](https://www.hostwinds.com/guide/wp-content/uploads/2018/12/KyleM2018-12-27_18-11-21-bbb76066-e8ab-497d-9170-f7cf7ba23e90.png)

So - building on the great work of Virtualmin - here are some suggested action points:

1) make dashboard with icon User Interface similar to the above - the icons from your icon file would be great: https://authentic-theme.com/kit/
2) Have "sections" or "categories" on dashboard where similar functions are grouped (e.g. all the database functions are grouped under the heading "Databases" etc...)
3) Possible to allow users to drag and drop the sections to be able to customise / personalise the dashboard - and even (as sys-admin) decide which sections to hide in the UI.
4) when you click on e.g. "Edit Databases" - rather than showing the tabs at the top (Databases / Usernames / Passwords / Remote Hosts etc....) these could be replaced with icons to click on - it's just an aesthetic thing!

5) Possible to enable access to e.g. roundcube / email from within virtualmin / rather than having to go to usermin - or is that beyond the ability of the theme.

I'm sure others could chime in....  But if you could make the end-user experience a bit more intuitive, it would help enormously.

I am also willing to assist you where possible.  

Thank you for listening and for your work.

_Originally posted by @solaceten in https://github.com/authentic-theme/authentic-theme/issues/896#issuecomment-531081170_

**Comment by rostovtsev** [comment]
At first, thanks for your kind wishes and words.

> Virtualmin is really a bit confusing and not very intuitive for "end-user" (e.g. a web hosting customer) 

Do you mean _server owner_ users, not master admins, right?

>  You have the icons UI laid out nicely in front of you and it's very intuitive to know where to click for the function you need.

In case the answer for previous question is _yes_, it's more or the less realistic to make it displayed alike (as cPanel) for _server owners_ and _Usermin_ users. The idea behind, as I see it at the moment, is to render left (navigation) menu into separate page, with icons and links, grouped by category; on that new navigation page, clicking on the icon, would open expected module/section.

> Have "sections" or "categories" on dashboard where similar functions are grouped (e.g. all the database functions are grouped under the heading "Databases" etc...)

Possible, as logical continuation to new navigation page (just mentioned above) but requires quite a bit of work. :sweat_smile: 

> When you click on e.g. "Edit Databases" - rather than showing the tabs at the top (Databases / Usernames / Passwords / Remote Hosts etc....) these could be replaced with icons to click on - it's just an aesthetic thing!

That in particular, should be changed/coded on the module side. Doing it on the theme side is possible but completely undesirable.

> How to enable access to e.g. roundcube / email from within Virtualmin rather than having to go to Usermin - or is that beyond the ability of the theme.

I am not sure exactly what the question is about? You can make RoundCube link or any other link appear on the navigation menu for easy access, by editing _Navigation menu options/Extra entries_ in theme configuration.

**Example:**

```JSON
{
   "extra":[
      {
         "title":"Google Mail",
         "link":"https://gmail.com/",
         "icon":"google",
         "level":"0,1,2,3,4"
      },
      {
         "title":"BIND DNS Server",
         "link":"/bind8",
         "icon":"server"
      }
   ]
}
```

----

Speaking about mail, in the near future, you might want to give up other web-mail clients, as I'm actively working on [new mail UX](https://github.com/authentic-theme/authentic-theme/issues/431#issuecomment-529125690).

Thank you for your time and comments.

**Comment by solaceten** [comment]
Hi thank you for opening new thread - easier ;-)

Answers to your points:

>> Virtualmin is really a bit confusing and not very intuitive for "end-user" (e.g. a web hosting customer)
> Do you mean server owner users, not master admins, right?

Correct - "virtual server" or end-user or / webhosting customer in my opinion. Sys-admin is root = master admins... So yes, it is a bit confusing as virtual server owner when you log in to manage your domain or email etc.  

> ... it's more or the less realistic to make it displayed alike (as cPanel) for server owners and Usermin users. The idea behind, as I see it at the moment, is to render left (navigation) menu into separate page, with icons and links, grouped by category; on that new navigation page, clicking on the icon, would open expected module/section.

Yes, it would make sense to have Nav on left and on right would be displayed with category / icons and clicking on any of those will take you to that module.

Let me know if I can help you realize the UX design for template start.

>How to enable access to e.g. roundcube / email from within Virtualmin rather than having to go to Usermin - or is that beyond the ability of the theme.
>I am not sure exactly what the question is about?

I just think it is good idea to have capability to access email (usermin) from virtualmin - but I was not aware you can make it customised as you've suggested, so please disregard this point - and yes, looking forward to seeing new mail

Let me know what help you need (I am not big programmer, but can help with design ideas :-)

**Comment by rostovtsev** [comment]
This will be a while though.

Thank you for offering the help. I'll let you know if I need it.

At first I need to finish mail view. It's a large section. Then, I was going to do few things for File Manager, like add ACL support. Afterwards, few things needed to be done for Dashboard, and in the end, I can handle this issue. 

I think, I will put all of this to 19.40 release.
