### ISSUE TITLE
Postfix: configuration check page rework

### ISSUE THREAD

**Issue by JimTR** [webmin/authentic-theme#1499]
Just a couple of issues
<img src="https://i.imgur.com/ONGi0OY.png" /> and <img src="https://i.imgur.com/Q1of2Ta.png" /> with the second one I guess this affects just the dark theme ... to date I have not tried in the light theme

**Comment by iliarostovtsev** [comment]
Hi, Jim.

For the first bug - fixed. For the second `postfinger.cgi` needs a rework, using UI lib. We'll do it when have time.

**Comment by iliajie** [comment]
This issue was fixed recently! Closing this!
