### ISSUE TITLE
Dashboard: Servers status

### ISSUE THREAD

**Issue by dpark77** [webmin/authentic-theme#1574]
I installed virtualmin with --minimal flag on Debian 10.

Servers listed in Servers Status section isn't functioning at all or doesn't get updated to reflect the latest changes. 

e.g.  System -> Bootup and Shutdown:
Stop Apache.

In Dashboard, Servers status
Apache is still shown as running.

so I click on stop(x) manually and go back to
Bootup and Shutdown to re-enable apache,
again it's not updating in Servers Status.

fwiw,  Servers status functions correctly in Centos 7 minimal install, but not in Debian 10.

**Comment by iliarostovtsev** [comment]
Hi,

@dpark77 For the Dashboard the status is cached and would require you to refresh system information manually or wait for scheduled collection to happen in background. For your Debian 10 machine, have a look at **System and Server Status ⇾ Configuration: Configurable options** and its **Status to display in list** to be set set to **Current status** to reflect actual monitors' state without caching.

@jcameron Jamie, should we consider the option **Status to display in list**, (which is set in **System and Server Status** config) to act accordingly when gathering data for the Dashboard (i.e. when set to **Current status** not to cache it for the Dashboard as well as we do for the module with this option), meaning to avoid caching with **Status to display in list** set to **Current status** and perform caching when it's set to **From last scheduled check** (as we do now unconditionally).

**Comment by jcameron** [comment]
@iliarostovtsev we could do that, but it would make the dashboard slow to load if the user has a lot of complex status checks. Unless we can load that one tab asynchronously?

**Comment by iliarostovtsev** [comment]
>  Unless we can load that one tab asynchronously?

Yeah, I could do it. Do you think it would be good to have?

**Comment by jcameron** [comment]
Yes, that would be useful if we expect status monitors to take a long time to load..

However, it would mean changing the way the overall status is fetched so that it isn't done in one call.

**Comment by iliarostovtsev** [comment]
> Yes, that would be useful if we expect status monitors to take a long time to load..

Will do.

**Comment by dpark77** [comment]
> Hi,
> 
> @dpark77 For the Dashboard the status is cached and would require you to refresh system information manually or wait for scheduled collection to happen in background. For your Debian 10 machine, have a look at **System and Server Status ⇾ Configuration: Configurable options** and its **Status to display in list** to be set set to **Current status** to reflect actual monitors' state without caching.
> 
> @jcameron Jamie, should we consider the option **Status to display in list**, (which is set in **System and Server Status** config) to act accordingly when gathering data for the Dashboard (i.e. when set to **Current status** not to cache it for the Dashboard as well as we do for the module with this option), meaning to avoid caching with **Status to display in list** set to **Current status** and perform caching when it's set to **From last scheduled check** (as we do now unconditionally).

sorry for my delayed followup

It was already set to "Current Status". It appears that's a default setting in configuration.
It still doesn't get updated in real time
but when I rebooted the system,
all the disabled modules have disappeared in Servers Status which is nice
and only the currently running modules are shown.
I just wished it wouldn't take so long or having to reboot updates it.

I just like how it's updated and reflected immediately in Centos.

**Comment by iliarostovtsev** [comment]
> Unless we can load that one tab asynchronously?

Do you mean doing this on Dashboard or the module itself? Or both?

**Comment by jcameron** [comment]
On the dashboard, since the server status is just one part of it, and the user would expect the other parts to load quickly..

**Comment by iliajie** [comment]
This will be implemented on the next theme release. It will only update in the background though, so no to keep the user waiting on the initial dashboard load, therefore it will take a few seconds to update the status (after the dashboard was initially loaded).
