### ISSUE TITLE
File Manager: Hide files starting from dot

### ISSUE THREAD

**Issue by TongTC** [webmin/authentic-theme#1578]
@iliajie 

Good Morning.

I would like to  ask for how to hide the dot file in file manager? 

Is there configuration for change ?

Please refer picture below:

![Screenshot 2022-01-28 094542](https://user-images.githubusercontent.com/56378146/151478569-37f9b7a1-4c55-450c-805c-1dd9d2e8cac1.png)

Best Regard

**Comment by iliarostovtsev** [comment]
Hi,

There is no way to hide files starting with a dot.

**Comment by jcameron** [comment]
That might be a nice feature, as it would match how the `ls` command works.

**Comment by TongTC** [comment]
@iliarostovtsev @jcameron 

OK , Thank you for your support.

Best Regard

**Comment by iliarostovtsev** [comment]
> That might be a nice feature, as it would match how the `ls` command works.

Okay, I'll have a look.

**Comment by iliajie** [comment]
Next Authentic theme release 21.07 will have support for hiding dotfiles.
