### ISSUE TITLE
Make the Reboot and Shutdown buttons customizable?

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1588]
I need to use a custom command when i shut down my RPi through Webmin. Is it possible to make the Reboot and Shutdown buttons customizable, so it is possible for me to shut down my RPi from the `Authentic theme`?

I use a HAT that controls the power to my RPi, so i can't use the shutdown command as it is.

**Comment by iliajie** [comment]
Hi,

Yes, have a look at **System ⇾ Bootup and Shutdown ⇾ Configuration: System configuration**, there is a way to configure _reboot_ and _shutdown_ commands.

**Comment by Sopor** [comment]
How could I be so blind? I have been in here and looked around several times without seeing it.

Sorry that i bothered you with it...

**Comment by iliajie** [comment]
No problem, you are welcome.
