### ISSUE TITLE
The cancel button missing for chorme , firefox , edge in Windows

### ISSUE THREAD

**Issue by TongTC** [webmin/authentic-theme#1589]
Hello @iliajie 

I would like to inform you about the cancel button for file uptracker.

I have tested  If I access  host from Linux or Mobile Phone it do not have problem.

but I  tested  accessing from Windows by browser the cancel button are missed(Refer in the attached picture).

Could you let me know how to fix it ?

Thank you.

Best Regard
<img width="955" alt="Untitled" src="https://user-images.githubusercontent.com/56378146/161660382-e3a20b30-8cca-4b60-b5a0-d99d297e71d0.png">

**Comment by iliajie** [comment]
Hi, 

> but I tested accessing from Windows by browser the cancel button are missed(Refer in the attached picture).

What browser are you using on Windows? What Windows versions is that? Have you tried the other browser, like Chrome or Firefox?

**Comment by TongTC** [comment]
> Dear Ilia

Yes, I'm using any browser(Firefox, Chrome ) on Windows11 and Windows 10.

But for Ubuntu I have check it work normal for any browser.

Best Regard

**Comment by iliajie** [comment]
Okay, I see the issue now. It will be fixed on the next release.

Thanks for reporting it.

**Comment by TongTC** [comment]
Thank you so much

Best Regard
