### ISSUE TITLE
Need a way to add GitHub Credentials to get past API Limitiations

### ISSUE THREAD

**Issue by JSylvia007** [webmin/authentic-theme#1590]
Is it possible to add my own github credentials to bypass the GitHub API limit?  I need to update multiple servers at once, and it seems I'm being rate-limited.

**Comment by iliajie** [comment]
As the **`git clone`** command on the them repo runs on your server, it must be possible with some local Git configuration.

Perhaps, [this thread](https://stackoverflow.com/questions/35942754/how-can-i-save-username-and-password-in-git) could help. 

Either way, you need to try really hard to reach rate-limit. 🙂 All those servers behind NAT and have a single external IP?

**Comment by JSylvia007** [comment]
So... I don't think the status is cached in any way, which means that as soon as you refresh the dashboard, it does another git request.  I have about 15 VMs, so apparently it didn't take too much.  You're correct that they're all NAT'd.

After an hour expired I was able to get in and update.  If it happens again I will have to see about storing my creds.  I do this already on other servers for other projects...  I didn't even think to try that here.

**Comment by iliajie** [comment]
> I don't think the status is cached in any way, which means that as soon as you refresh the dashboard,

It does get cached! You should check **Theme Configuration: Theme updates** page and its **Interval for running updates check** option.

Also, try hitting **Clear Cache** button and see if that solves your issue.

**Comment by JSylvia007** [comment]
Oh, I had definitely hit my API limit.  It said as much in the error, and when checking the API dashboard.  I don't know how, but I hit it LOL.

I'm good for now, but it was frustrating.  If I encounter the issue again, I will probably just store my creds for the user and see if that helps.
