### ISSUE TITLE
Buttons invisible unless hovered upon: feature, or bug, not sure sorry

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [webmin/authentic-theme#1591]
In virtualmin's entry page, I only today noticed the existence of 3 feature buttons next to texts, as my mouse pointer hovered above them.

Are they intentionally hidden, or ought they be visible at all times, I'm not sure, but that's potentially not intentional, so I'm reporting it, just in case. Sorry for the bother if I guessed it wrong.

I recorded it to https://www.youtube.com/watch?v=m9OiVKhwRQE

It's becoming noticeable 4 seconds into the video, there are  black emoji-like buttons becoming visible when the mouse pointer hovers above the value (not the texts themselves, their value) for "Webmin version", "Virtualmin version", and "Authentic theme version". Respectively, those buttons point to the webmin documentation, the virtualmin documentation, and the authentic theme configuration.

Having Authentic's configuration only reachable through a button that's hidden unless the mouse hovers above Authentic's version number is what convinced me to file this bug report, maybe it is not intentional.

Context info: webmin 1.990, virtualmin 6.17-3, debian buster, authentic 19.90, Firefox 99.0.1 with ublock origin.

Good day everyone, thank you for all the great work!

**Comment by iliajie** [comment]
Hi, Oliver!

> Are they intentionally hidden, or ought they be visible at all times, I'm not sure, but that's potentially not intentional, so I'm reporting it, just in case.

In-fact that was intentional. If the page is focused and you hover over those relevant rows the buttons will be shown. I just didn't want to clutter UI with those extra buttons shown all the time.

I am still not sure if those should be always visible.

> thank you for all the great work!

Thank you for your report.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
OK, duly noted, and my bad :)

**Comment by iliajie** [comment]
Thanks for your suggestion, Oliver. The next release will have those buttons always visible.
