### ISSUE TITLE
How to supress or customize that "Virtualmin" word while loggin in?

### ISSUE THREAD

**Issue by alanmels** [webmin/authentic-theme#1592]
Subj. It loads for just a fraction of time while logging in. Would like to customize it if possible.

**Comment by jcameron** [comment]
@iliajie is there a way to override or skip this intro graphic in the theme?

**Comment by iliajie** [comment]
I don't understand what the question is @alanmels ?

Can you show me the screenshot of what word and where exactly you are trying to customize?

**Comment by alanmels** [comment]
Привет Илья,

Очень непросто словить момент, чтобы взять скриншот. Короче, мы используем вот такую форму для авторизации:

```
<form target="_blank" action="https://nargs.org:10000/session_login.cgi" method="post">
<input type="submit" value="Log in">
<input type="hidden" name="user" value="username">
<input type="hidden" name="pass" value="password">
</form>
```

то есть, пользователи не вводят данные, а просто нажимают на кнопку Log in. Так вот, когда происходит переход на мгновение в центре экрана появляется надпись Virtualmin. Вот как его кастомизировать?

**Comment by iliajie** [comment]
Now I understand what you mean.

Have a look at this:


**Custom:**
```
/etc/webmin/authentic-theme/brand";
```

**Default:**

```
/usr/libexec/webmin/authentic-theme/images/brand
```

Also a splash screen can be disabled completely. When logged in as root, open browser's console and run the following JavaScript codes:

```
settings_embed_product_branding_privileged = false;
theme.config.save();
```

**Comment by alanmels** [comment]
Thanks for the pointer!
