### ISSUE TITLE
Strange local disk size usage indication

### ISSUE THREAD

**Issue by fdmgit** [webmin/authentic-theme#1593]
I've just install a new server (Ubuntu 20.04) with Virtualmin.
Checking the dashboard, I was surprised by the used local disk space (see pic 1). The usage is far to high !

Did a check from the CLI and that looks very reasonable (see pic2)
Am I overlooking something?

Pic 1

![2022-05-06_12-47-33](https://user-images.githubusercontent.com/29498370/167120578-708f0fa2-b43e-4daa-b0e4-096e14392b34.png)

Pic 2

![2022-05-06_13-01-27](https://user-images.githubusercontent.com/29498370/167120659-a79e8cf2-9061-41a9-8d00-9364e1b0b888.png)

**Comment by iliajie** [comment]
What is the output of:

```
free -mh
```

**Comment by fdmgit** [comment]
Output:

root@bi:/# free -mh
              total        used        free      shared  buff/cache   available
Mem:           31Gi       491Mi        29Gi        23Mi       1.2Gi        30Gi
Swap:         530Mi          0B       530Mi

**Comment by iliajie** [comment]
What does clicking refresh button on the top right of the Dashboard change?

**Comment by fdmgit** [comment]
No change. Same resulte as before.

**Comment by iliajie** [comment]
Without taking a deeper look, I have no clue what's wrong, sorry.

**Comment by jcameron** [comment]
Those `/snap` filesystems might be an issue. What are they used for?

**Comment by fdmgit** [comment]
I don't use snap at all. As far as I remember the snap filesystem was created by the standard Ubuntu server installation.

I've now uninstalled snap incl. snap packages, cache etc.
But the effect is minimal, still over 20G of used disk space according to the Virtualmin dashboard

P.S: I have the same effect on a different Ubuntu server. The server is a new installation done 2 days ago.

**Comment by jcameron** [comment]
Can you attach a screenshot of the filesystems shown at System -> Disk and Network Filesystems?

**Comment by fdmgit** [comment]
![pic3](https://user-images.githubusercontent.com/29498370/167281173-79036384-83cb-4f1a-b9ab-a58b6d7f9424.png)

**Comment by jcameron** [comment]
If you click on the root filesystem, how much disk space does it show as available and in use on the FS?

**Comment by fdmgit** [comment]
![pic4](https://user-images.githubusercontent.com/29498370/167284088-4740e32c-cf5d-4a5b-9c43-30bf3e13f624.png)

**Comment by jcameron** [comment]
Ok I see now - the "used" disk space shown by Virtualmin includes space that is reserved for the `root` user, and so it's accessible to regular Virtualmin server users. This is usually about 5% of total disk space.
