### ISSUE TITLE
Change Language and Theme - Change the way the `Output example` show up

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1594]
Please do something about the `Output example` that will show up when making it active and hovering the mouse pointer over.

Try to copy values from one Webmin in to another (especially with many patterns). This `Output example` is in the way all the time when trying to edit the patterns.

Sometimes you even have two `Output example`, one where the cursor is (the active) and one where the mouse pointer is.

![image](https://user-images.githubusercontent.com/5789283/167218721-9d423c9b-f571-4953-aa62-a9bf0a2464f7.png)

I need to move the mouse around the `Output example` and the input values because if I hover the mouse pointer over one of them the `Output example` is showing up again.

Is it possible to have them to the right instead of below? Maybe you have a better solution?

Windows 10
Firefox 100.0

**Comment by iliajie** [comment]
What about just using the tab key to switch between inputs?

**Comment by Sopor** [comment]
I'm a mouse guy and prefer to use the mouse (that is why i use Windows). Fiddling with the keyboard is for the guys using command line 😀

**Comment by iliajie** [comment]
Okay, I have taken a closer look and fixed it. No wonder it didn't work well, the code was utter nonsense.
