### ISSUE TITLE
Refresh button after reboot will work as a back button

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1595]
If i go to `System / Bootup and Shutdown / Reboot system` the computer will reboot and it will show a message that it has lost the connection.

When the system is back up and running it will tell my that and it will load the dashboard.

If i now press the Refresh button on the left side it will not refresh the dashboard.
![image](https://user-images.githubusercontent.com/5789283/167970847-e3e441e7-d11e-4b86-a99f-3bef7c33cbbe.png)

Instead it will show this message:
![image](https://user-images.githubusercontent.com/5789283/167970672-e010912a-6165-422c-8b17-581add9d3ede.png)

The refresh button seems to work as a back button. Every time i click on it i go back to the previous page. So, if i open Theme configuration and i select Theme updates and then go back to the dashboard and press the refresh button i'm back to the Theme updates again. The only way out of this is to clear cache.

Authentic theme version 19.91.3
Firefox 100.0
Windows 10

**Comment by Sopor** [comment]
This still happens in Authentic theme version 19.98.

**Comment by jcameron** [comment]
@iliajie looks like a theme issue?

**Comment by iliajie** [comment]
Yeah, but a minor one. Will fix that. This is not very important and cannot hold off the release.

**Comment by iliajie** [comment]
Alright, this will be fixed in upcoming release.
