### ISSUE TITLE
Edit Cron job - Next run time: Unknown

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1596]
I have a cron job set to run `Monthly (on the 1st)` but the `Next run time` will show `Unknown`. I don't know if this is a Cron job, Authentic theme or Webmin issue.

![image](https://user-images.githubusercontent.com/5789283/167972564-fac41f13-969b-4967-a5fa-0cdce17800fc.png)

**Comment by jcameron** [comment]
Thanks for pointing this out - it will be fixed in the next release.
