### ISSUE TITLE
manifest-webmin.json "Failed to load resource" error 404

### ISSUE THREAD

**Issue by ludovicsclain** [webmin/authentic-theme#1597]
Hi there,
Since the last update, I currently have a 404 error in my console with a manifest-webmin.json [https://myserver.com/manifest-webmin.json] file not found. 

`manifest-webmin.json:1 Failed to load resource: the server responded with a status of 404 (File not found)`

Did the update go wrong? Did I miss something? 
Thank you for your help !
Warm regards,
Ludovic

**Comment by iliajie** [comment]
Hello, Ludovic.

> Since the last update, I currently have a 404 error in my console with a manifest-webmin.json [https://myserver.com/manifest-webmin.json] file not found.

Did you install update using package manager (i.e. installed Authentic Theme with `webmin` package update) or upgraded the theme using Git on the prompt in the IU?

What is currently installed theme version?

**Comment by ludovicsclain** [comment]
Thank you for your reply, 
my version is 19.91.3 updated from the usual "Package updates" menu from the dashboard
https://markuphero.com/share/OGJZkUtIb4tSXeAYxmoU

**Comment by iliajie** [comment]
Do you still see this issue after installing Webmin 1.994?

**Comment by ludovicsclain** [comment]
You're right, all seems correct now, thank you!
