### ISSUE TITLE
Recent logins - multiple logins from the same IP address

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1598]
Why will it show multiple logins from the same IP address?

![image](https://user-images.githubusercontent.com/5789283/169542564-5c448762-f188-4e29-ad7a-26212ee2a164.png)

**Comment by iliajie** [comment]
Because those are different sessions.

**Comment by Sopor** [comment]
Why will it create different sessions?

How long will the stay as `Logged in`? The user is not logged in 4 times. Shouldn't it detect that and change it to something else?

**Comment by jcameron** [comment]
This could be due to multiple browsers or incognito windows on the same machine?

**Comment by Sopor** [comment]
It seems that the user have used incognito, so that will probably explains it.
