### ISSUE TITLE
Theme: improve color contrast ratios for ADA compliance

### ISSUE THREAD

**Issue by adamzea** [webmin/authentic-theme#1599]
The dark mode "nightRider" theme style is pretty nice, but many sections have very low contrast ratios between the type color and background color. This makes type difficult to read especially for people with slight (or growing) vision impairments.  A contrast ratio of 7 is preferred.  See: https://www.w3schools.com/accessibility/accessibility_color_contrast.php
A contrast ratio of at least 4.5 is required for ADA compliance. See: https://adacompliancepros.com/the-2021-checklist-for-an-ada-compliant-website/
4.5 is also the minimum recommendation for the World Wide Web Consortium (W3C) Web Content Accessibility Guidelines. 
See: https://www.w3.org/TR/WCAG21/#contrast-minimum
Some areas of your theme design are under 3 in terms of contrast ratios.

You can see contrast ratio number calculations pretty easily with the Chromium inspector tool.  See below screenshots:
https://ibb.co/fpyXBqT
https://ibb.co/yRtPrsQ

I was able to fix most of those issues myself using the Theme Extensions CSS editor to override colors, but having good accessibility by default is probably a better idea.

**Comment by iliajie** [comment]
Infact, I really thought I fixed it all for the dark palette with latest release.

I will review it over again. Thanks.

**Comment by swelljoe** [comment]
Ilia likes to punish folks with bad vision. (I yell at him about it all the time.) ;-)

**Comment by iliajie** [comment]
I'm sorry. I don't.

If you check my latest commits, from earlier today, yesterday and a day before yesterday, you will notice that I have been improving the contrast for the default palette already.

Dark palette was reworked too on the previous release. But I will be happy to make it even more contrast before a release later today.

**Comment by adamzea** [comment]
Oh, sorry. I thought I was up to date with version 19.91.2, but I now see there's a new build that hasn't gotten to me yet.  Thank you for already being on top of the contrast ratio improvements!

**Comment by iliajie** [comment]
The element that you have shown in a screenshot (a link), alongside with a panel title were the only missed elements when  previous rework was done, where I remember making sure to follow accessibility.

Links also look good now, although to me they stand out to much.

Example:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/4426533/169605090-053b221e-de24-4041-add0-3f821e30ace0.png">


<img width="1128" alt="image" src="https://user-images.githubusercontent.com/4426533/169604865-aa10a62d-0b7c-42e8-9b86-c35439cc90b5.png">

**Comment by iliajie** [comment]
Ah, _This Login_ also an issue.

**Comment by iliajie** [comment]
Labels and badges were fixed to. Give it a try when Webmin 1.992 is out.

> I was able to fix most of those issues myself using the Theme Extensions CSS editor to override colors, but having good accessibility by default is probably a better idea.

Can I have a look at it?
