### ISSUE TITLE
Virtualmin Git plugin error 

### ISSUE THREAD

**Issue by lvarela** [webmin/authentic-theme#16]
When the Virtualmin Git plugin is installed, clicking on "Repository Commands" or "Browse Repository" it will display an error page with the message: "No button clicked!"

This error is only displayed when using the authentic theme. I used version 4.2.0.

**Comment by recursosformacion** [comment]
Virtualmin version 5.02 .... same

**Comment by qooob** [comment]
What theme version you're having installed?

**Comment by recursosformacion** [comment]
Authentic Theme 18.00

Webmin 1.795

Virtualmin 5.02

In Centos 6.7

 

De: Ilia Rostovtsev [mailto:notifications@github.com] 
Enviado el: jueves, 08 de septiembre de 2016 20:19
Para: qooob/authentic-theme <authentic-theme@noreply.github.com>
CC: recursosformacion <migarcia@recursosformacion.com>; Comment <comment@noreply.github.com>
Asunto: Re: [qooob/authentic-theme] Virtualmin Git plugin error (#16)

 

What theme version you're having installed?

**Comment by qooob** [comment]
No wonder you have those issue.

Upgrade to the latest Webmin 1.810 (shipped with latest Authentic Theme 18.10).

**Comment by renaissance-design** [comment]
I'm seeing the same problem.

CentOS 6.8
Webmin 1.810
Virtualmin 5.04
Authentic 18.10

**Comment by qooob** [comment]
Dupe #https://github.com/qooob/authentic-theme/issues/546

**Comment by qooob** [comment]
It will be fixed in 18.20

**Comment by jmcabandara** [comment]
Error
No button clicked! 

I have also same issue and kindly tel us at least how to fix it.

Thank you in advanced

**Comment by qooob** [comment]
Just upgrade to theme version 18.31
