### ISSUE TITLE
Statistics graphs have vanished

### ISSUE THREAD

**Issue by philmck** [webmin/authentic-theme#1600]
The whole "statistics" accordion with all the graphs has vanished from all my servers since the most recent update.

Perhaps a regression of https://github.com/webmin/authentic-theme/issues/386?

Webmin version 1.994, Authentic theme version 19.93.1 running on Ubuntu (16.04, 18.04 and 20.04).

**Comment by iliajie** [comment]
Hello, Phil.

We are working on fixing it. Sorry about that.

The work around would be is to login as system `root` user.

**Comment by iliajie** [comment]
This has been fixed on Webmin 1.998+.
