### ISSUE TITLE
The horizontal scrollbar of the log window disappears

### ISSUE THREAD

**Issue by pacquo** [webmin/authentic-theme#1601]
Hello Ilia,

I have installed Authentic 19.93.1 version on Webmin 1.994 (minimal package) and I'm using Firefox 100.2.

I use Webmin mainly to read logs; despite the last update (issue: Scrollbar accessibility #1584) the scrollbars of the log window are barely visible.

The horizontal scrollbar, in particular, disappears most of the times after a few seconds, while other times it's visible until you start to scroll the log vertically. In both cases it doesn't reappear until you hit the "refresh" button.

Even when it's visible it's really difficult to grab, being almost transparent and very thin.

Kind regards,

Andrea

**Comment by iliajie** [comment]
Hello,

Thank you for the heads up. You are right, the scrollbars needs a fix. This is done now with the latest commit.

**Comment by pacquo** [comment]
Hello Ilia,
I am here again for a quick update.

I have installed Webmin 1.996 with Authentic 19.95.2, and I see that the problem I mentioned earlier - the horizontal scrollbar of the log window that hides itself - still happens with Firefox (I'm now using the 102.0.1 version) while it does not happen with Edge, for example. 

This had led me to investigate a little deeper, until I've found this line of code:

``<div class="CodeMirror-hscrollbar" tabindex="-1" cm-not-content="true" style="right: 0px; left: 0px; height: 18px; display: block; pointer-events: none;">``

Changing the property of the selector ``pointer-events`` from ``none`` to ``auto`` the horizontal scrollbar stays visible as expected.

Kind regards,

Andrea

**Comment by iliajie** [comment]
Howdy, Andrea!

I am testing a new theme pre-release now, and in 20-30 minutes I will add CodeMirror update that fixes few recent bugs that people reported.

Although, perhaps this is Firefox an adoption of some Windows features?

https://connect.mozilla.org/t5/discussions/scrollbars-disappear-in-firefox-100/td-p/5433

**Comment by pacquo** [comment]
> Although, perhaps this is Firefox an adoption of some Windows features?

It look like it, Ilia! I have Windows 11 and indeed the "Always show scrollbars" setting under the _Accessibility_ menu is disabed by default, as you pointed out. 
Enabling it fixes the problem. I stumbled into one of the dark corners of Windows evidently... thank you for the suggestion!

Andrea

**Comment by iliajie** [comment]
Glad to hear it works for you!
