### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by sam-anam1** [webmin/authentic-theme#1604]
its probably would be really helpful!

- in Virtualmin when switch between virtual servers it would be cool if support  File Manager,.. Apache Access/Error Logs  that change. 
Exp. (which currently when switch virtual domain and on Bandwidth Graph it will change to chosen vhot Bandwidth Graph page)

- Disable Auto Zoom input focus on mobile devices when client username in login page or in file editor or any inputs that it page will zoomed.

- Add (Bandwidth Usage) in Virtualmin Configuration --> User Interface Setting --> Columns to show

- Auto Save "**Toggle Soft Wrap**" setting when Virtualmin user make on/off or an option make alway off / on

- Editor Keyboard Shortcuts with file editor, **the replace keys (Ctrl + H) = Replace and  (Ctrl + ⇧ + R) = Replace all**. 
 it should be changed as MacOS it doesn't work.. 
Command + h (Ctrl + H) = Window Hide the window, 
Command + shift + r (Ctrl + ⇧ + R) = homepage url.

- Shortcut icon for Edit file in File Manager  btn group top right menu.

**Comment by jcameron** [comment]
@iliajie these sound like good theme / UI suggestions?

**Comment by iliajie** [comment]
Can do.

Although, I didn't understand about bandwidth and short icon?

**Comment by sam-anam1** [comment]
Hello @iliajie
- Columns to show **"user bandwidth used"**  which is at System Settings -> Virtualmin Configuration --> User Interface setting. 
that to shows "bandwidth Usage" in  List Virtual Servers

![bandwidth Usage](https://user-images.githubusercontent.com/6969182/177012246-e6f2b325-5efd-45ba-a62e-1f94bc4c08d6.png)



- Short icon for Edit file in  File Manager
when select a file like .html or any editing extension.. it would be great Edit icon appear in top right.

![File Manager - Short icon for Edit](https://user-images.githubusercontent.com/6969182/177012276-54f6b932-22dc-45e8-b66c-d972a8c5e2aa.png)

**Comment by iliajie** [comment]
> * Columns to show **"user bandwidth used"**  which is at System Settings -> Virtualmin Configuration --> User Interface setting.
>   that to shows "bandwidth Usage" in  List Virtual Servers

This is Virtualmin feature request. @jcameron Jamie, do you intentionally not adding bandwidth column?

> Short icon for Edit file in File Manager when select a file like .html or any editing extension.. it would be great Edit icon appear in top right.

That I won't do. There is F4 (edit) and F3 (view) hotkeys for that already. And context menu (right click) is faster than reaching up .. and file manager don't do it either ..

The rest of the features request will do after Virtualmin 7 release.

**Comment by iliajie** [comment]
Number 1 requested feature was implemented (when switch domains). It adds support for all `virtualmin-*` modules, for File Manager, and various logs and web services too.

**Comment by iliajie** [comment]
> Disable Auto Zoom input focus on mobile devices when client username in login page or in file editor or any inputs that it page will zoomed.

There is no good cross-platform solution for this, sorry. I would suggest to try Chrome on iOS.

**Comment by sam-anam1** [comment]
> > Disable Auto Zoom input focus on mobile devices when client username in login page or in file editor or any inputs that it page will zoomed.
> 
> There is no good cross-platform solution for this, sorry. I would suggest to try Chrome on iOS.

We usually used to disable Safari from automatically zooming in on fields
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

**Comment by sam-anam1** [comment]
We usually used to disable Safari from automatically zooming in on fields
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`

**Comment by iliajie** [comment]
Yeah, I know. This however will prevent any zoom on other mobile devices. This is undesirable.

**Comment by iliajie** [comment]
> * Auto Save "**Toggle Soft Wrap**" setting when Virtualmin user make on/off or an option make alway off / on

This is already remembered across the browser.

**Comment by iliajie** [comment]
> * Editor Keyboard Shortcuts with file editor, **the replace keys (Ctrl + H) = Replace and  (Ctrl + ⇧ + R) = Replace all**.

We use Sublime keymap and thus there is no need to use `Ctrl + H`.

For replace on Mac you can already use `Shift-Cmd-F` or `Shift-Ctrl-F`.

**Comment by iliajie** [comment]
Better support for hotkeys on Mac was implemented!  I really wanted to do it a long time ago but never got down to it.

Finally, it was improved: 

  1. All hotkeys are now named properly across interface (titles, tooltips and popovers)
  2. Hotkeys on Mac are flipped as they meant to be for most actions, for example `Command + C` and `Command + V` will actually copy/paste files and File Manager and `Command + S` and `Command + Shift + S` will save as
  3. Some hotkeys were shortened in file editor/viewer, for example to toggle wrap now is `Option + W` (`Alt + W`), file refresh is `Option + R` or `F2`, switching between tabs in file manager is `⌘ + arrow left` and `⌘ + arrow right` (For Linux/Windows users it's `Ctrl + arrow left` and `Ctrl + arrow right`)
  4. As bonus added new hotkeys to access module configuration (when possible) by clicking `⌘ + ,` or accessing theme configuration page by clicking `⌘ + ⇧ + ,`
  5. Added hotkeys to navigate inside module config and switch from next to previous config page by clicking `⌘ + arrow left` and `⌘ + arrow right`.
  
Give it a try and tell me if you find anything that was left off.

**Example:** 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4426533/178066595-f60fef36-0b04-4325-96a7-7bfe88488108.png"> <img width="400" alt="image" src="https://user-images.githubusercontent.com/4426533/178066502-cd73d30b-8c00-4869-b570-87a7cf04b095.png">

**Comment by iliajie** [comment]
I consider this ticket as solved. Please open a new ticket at [Virtualmin repo](https://github.com/virtualmin/virtualmin-gpl) about adding _Bandwidth Usage_ column.
