### ISSUE TITLE
Extra button for Update Packages page

### ISSUE THREAD

**Issue by BrettRow** [webmin/authentic-theme#1605]
The Package Updates page has an update button above and below the list of updates:

![image](https://user-images.githubusercontent.com/8628540/177917888-c9e4be02-6782-4d56-a343-51f2d9b0f0cc.png)

It would be handy if the Update Packages page also had a button below the list as well as above:

![image](https://user-images.githubusercontent.com/8628540/177918021-f7a6a99c-c42b-4db6-b99f-cc8bf4247b62.png)

If there are a large number of updates, and you scroll down to see the end of a long list, you need to scroll back again to be able to click on the install button.

**Comment by iliajie** [comment]
Alright, good suggestion. Added it. Although, this is Webmin feature , not the theme. We will print that bottom button only when needed (like on a large updates).

Expect it in Webmin 1.997.
