### ISSUE TITLE
Javascript errors when clicking on Dashboard menu item

### ISSUE THREAD

**Issue by freebrowser1** [webmin/authentic-theme#1606]
When installing Webmin 1.996 on two different Ubuntu servers (20.04LTS), the left menu (which has 'authentic-theme') is unusable in Firefox (I use 101 and 102). It does not open and Element Inspector shows Javascript errors in `bundle.min.js` which is part of Bootstrap which is installed along with Webmin.
The weird thing is that it only occurs on Firefox on macOS (Monterey). The same FF version 102 on Ubuntu 22.04 does not show this issue and another browser on macOS (Brave, Safari) does not have this issue. 

See screenshots.

Click on one item here:
<img width="266" alt="Screenshot 2022-07-10 at 08 54 04" src="https://user-images.githubusercontent.com/26625141/178134691-fff96d7e-9379-4c5e-9167-8bd80655f318.png">

results in this: 

<img width="675" alt="Screenshot 2022-07-10 at 08 54 11" src="https://user-images.githubusercontent.com/26625141/178134695-feada110-6a86-4498-b5d0-055dc634fc3d.png">

A related error occurs in bundle.min.js when opening File Manager (https://[domain]/filemin/?xnavigation=1) on Firefox 102, both macOS and Linux.

It appears that `bundle.min.js` has an issue.

<img width="523" alt="Screenshot 2022-07-10 at 11 40 45" src="https://user-images.githubusercontent.com/26625141/178139703-f0451db9-7e74-4d6b-91e7-d32119ac823a.png">

**Comment by iliajie** [comment]
Is this a clean install or an upgrade from 1.994 or 1.995?

What is on 13634? It would be clearer if you beautify the code by clicking {} in the console, after clicking on 2:13634.

**Comment by freebrowser1** [comment]
It is a clean install.
Code like this ?

```
        v.push(',.*:')
      })), (n.matchesSelector = K.test(m = h.matches || h.webkitMatchesSelector || h.mozMatchesSelector || h.oMatchesSelector || h.msMatchesSelector)) && ce(function (e) {
        n.disconnectedMatch = m.call(e, '*'),
        m.call(e, '[s!=\'\']:x'),
        y.push('!=', F)
      }), v = v.length && new RegExp(v.join('|')), y = y.length && new RegExp(y.join('|')), t = K.test(h.compareDocumentPosition), x = t || K.test(h.contains) ? function (e, t) {
        var n = 9 === e.nodeType ? e.documentElement : e,
        r = t && t.parentNode;
        return e === r || !(!r || 1 !== r.nodeType || !(n.contains ? n.contains(r) : e.compareDocumentPosition && 16 & e.compareDocumentPosition(r)))
      }
       : function (e, t) {
        if (t) while (t = t.parentNode) if (t === e) return !0;
        return !1
      }, N = t ? function (e, t) {
        if (e === t) return f = !0,
        0;
        var r = !e.compareDocumentPosition - !t.compareDocumentPosition;
        return r || (1 & (r = (e.ownerDocument || e) == (t.ownerDocument || t) ? e.compareDocumentPosition(t) : 1) || !n.sortDetached && t.compareDocumentPosition(e) === r ? e == d || e.ownerDocument == w && x(w, e) ? - 1 : t == d || t.ownerDocument == w && x(w, t) ? 1 : c ? P(c, e) - P(c, t) : 0 : 4 & r ? - 1 : 1)
      }
       : function (e, t) {
        if (e === t) return f = !0,
        0;
        var n,
        r = 0,
        i = e.parentNode,
        o = t.parentNode,
        a = [
          e
        ],
        s = [
          t
        ];
        if (!i || !o) return e == d ? - 1 : t == d ? 1 : i ? - 1 : o ? 1 : c ? P(c, e) - P(c, t) : 0;
        if (i === o) return pe(e, t);
        n = e;
        while (n = n.parentNode) a.unshift(n);
        n = t;
        while (n = n.parentNode) s.unshift(n);
        while (a[r] === s[r]) r++;
        return r ? pe(a[r], s[r]) : a[r] == w ? - 1 : s[r] == w ? 1 : 0
      }),
      d
    }, se.matches = function (e, t) {
      return se(e, null, null, t)
    }, se.matchesSelector = function (e, t) {
      if (p(e), n.matchesSelector && g && !A[t + ' '] && (!y || !y.test(t)) && (!v || !v.test(t))) try {
        var r = m.call(e, t);
        if (r || n.disconnectedMatch || e.document && 11 !== e.document.nodeType) return r
      } catch (e) {
        A(t, !0)
      }
      return 0 < se(t, d, null, [
        e
      ]).length
    }, se.contains = function (e, t) {
      return (e.ownerDocument || e) != d && p(e),
      x(e, t)
    }, se.attr = function (e, t) {
      (e.ownerDocument || e) != d && p(e);
      var i = r.attrHandle[t.toLowerCase()],
      o = i && j.call(r.attrHandle, t.toLowerCase()) ? i(e, t, !g) : void 0;
      return void 0 !== o ? o : n.attributes || !g ? e.getAttribute(t) : (o = e.getAttributeNode(t)) && o.specified ? o.value : null
    }, se.escape = function (e) {
      return (e + '').replace(re, ie)
    }, se.error = function (e) {
      throw new Error('Syntax error, unrecognized expression: ' + e)  // <<<<<<<<<<<<<<<<<<<<<< HERE !
    }, se.uniqueSort = function (e) {
      var t,
      r = [
      ],
      i = 0,
```

<img width="750" alt="Screenshot 2022-07-10 at 11 55 57" src="https://user-images.githubusercontent.com/26625141/178140005-a9fe6b38-da26-4f15-896b-8b8141792dc2.png">

**Comment by iliajie** [comment]
> Code like this ?

No. I need the stack. Click arrow key to unfold the stack and show me the screenshot pelase: 
<img width="115" alt="image" src="https://user-images.githubusercontent.com/4426533/178141812-43208f42-b20e-4cf9-ad2a-227cf27bae92.png">

**Comment by iliajie** [comment]
Nevermind. I reproduced a problem. I will fix it in upcoming theme 19.96 release.

**Comment by iliajie** [comment]
Are there more errors? Does it happen in chrome? Did you install from source?

**Comment by iliajie** [comment]
I mean, what `HTTP/1.0 500 Perl execution failed` errors do you see in UI?

If nothing appears on UI, is anything logged into `/var/webmin/miniserv.error` file log with `Perl execution failed` error?

**Comment by iliajie** [comment]
Anyway, try installing latest development version of the theme using theme configuration page and let me know what changed for you.

**Comment by freebrowser1** [comment]
> > Code like this ?
> 
> No. I need the stack. Click an arrow icons to unfold the stack and show me the screenshot pelase: <img alt="image" width="115" src="https://user-images.githubusercontent.com/4426533/178141812-43208f42-b20e-4cf9-ad2a-227cf27bae92.png">
When I click on the arrow icon left of 'Uncaught' the same stack is shown. So I assume it is the call stack of the exception.

**Comment by iliajie** [comment]
I have fixed it. No need for anything else.

Please check `/var/webmin/miniserv.error` file log with `Perl execution failed error`! I'd like to see what initial problem was on your side?

Also, you can try latest devel version of the theme and check if that fixes the problem for you (it will, I'm sure though).

**Comment by iliajie** [comment]
> Where can I find the latest development version ?
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/4426533/178158628-54da71ff-0db2-43fa-88e6-c3ddf1d52db0.png">

**Comment by freebrowser1** [comment]
Same issue with 19.97. It happened after clearing cache. I opened it in a private window.



![Screenshot 2022-07-11 at 07 53 29](https://user-images.githubusercontent.com/26625141/178197948-ec9d04e1-55f4-440c-be94-ef25752f9989.png)

**Comment by freebrowser1** [comment]
Well, it *is* possible. On another server (ubuntu 20.04 as well), same issue.
I tried to install 19.97 but then I got this message:

_Installing this version of Authentic Theme 19.97 requires latest and/or possibly unreleased version of Usermin to work properly. There might be incompatible changes, that could stop the theme from working as designed. Continuing upgrade operation using UI is not possible._

Restarting webmin did not solve the problems.

**Comment by iliajie** [comment]
Can I login and have a look?

**Comment by iliajie** [comment]
.. and if you're seeing this message, then you're not installing it on Webmin 1.996.

**Comment by iliajie** [comment]
This initial issue is addressed. Thanks for reporting.
