### ISSUE TITLE
No update icon

### ISSUE THREAD

**Issue by nigel-aves** [webmin/authentic-theme#1607]
I've just noticed that I'm way behind on updates. There are no "update" icons showing in the Webmin interface. (For both Theme and Webmin) Not sure what to do to correct this.  I've checked using both Chrome and Firefox.

Nigel Aves.

![image](https://user-images.githubusercontent.com/33691546/180015324-de0d40d5-fdf3-4919-913e-4672a2ba2809.png)

**Comment by iliajie** [comment]
Hello, 

This is expected, as Virtualmin repos haven't received Webmin update yet.

**Comment by nigel-aves** [comment]
Illia,

That's a tad confusing when you have one icon that says there is an update!
:)

Nigel.

**Comment by iliajie** [comment]
Any update on this?
