### ISSUE TITLE
System Time - date: invalid date

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1608]
I have set my `System time settings format` to `YYYYMMDDHHMM.SS`
![image](https://user-images.githubusercontent.com/5789283/181351438-36570326-0580-4ebb-a2af-57543828d084.png)

When i try to change the time/date i get this error message
![image](https://user-images.githubusercontent.com/5789283/181351652-75b8168f-3ef4-4d58-a204-c7d4fdc9a82e.png)

To change the time/date i need to change the `System time settings format` to `MMDDHHMMYYYY.SS`.

<html><body>

Webmin version | 1.997
-- | --
<html><body>

Authentic theme version | 19.97
-- | --

</body>
</html>

</body>
</html>

**Comment by iliajie** [comment]
What OS and version is this happening on?

**Comment by Sopor** [comment]
DietPi - Debian Linux 11

**Comment by Sopor** [comment]
Same thing on Ubuntu Linux 18.04.6

**Comment by iliajie** [comment]
Let's just hide it then.

**Comment by jcameron** [comment]
Generally we put these kinds of settings in a separate section of the module config, called "System configuration" rather than hiding them entirely

**Comment by iliajie** [comment]
No, no. Not entirely. Hide it only for Linux. We have a facility for that (I remember adding one). Let me fix it...

**Comment by jcameron** [comment]
Send me PR for it

**Comment by iliajie** [comment]
Here you go - https://github.com/webmin/webmin/pull/1702/files

Although, I just noticed that for this feature to work flawlessly we need to preserve hidden key values. That would have to be implemented ..

**Comment by Sopor** [comment]
What i know the `MMDDHHMMYYYY.SS` is the default format...
