### ISSUE TITLE
Copy basic system information to clipboard

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1610]
What are the keys i need to hold?
![image](https://user-images.githubusercontent.com/5789283/181803241-286da8c9-e213-49fe-8015-f4093f686d1c.png)

**Comment by iliajie** [comment]
It depends on what type of system information you want to be copied to clipboard?

I suggest looking at the bottom-left side of your Mac keyboard, to find mentioned in a tooltip keys.

**Comment by Sopor** [comment]
Why do you think i asked? I don't own a Mac and i will never do. I'm allergic to apple.

I'm running Windows 10 and Firefox 103.

**Comment by iliajie** [comment]
Ah, you're right. I missed it for this particular part. Thanks, it's fixed on the latest commit.

**Comment by Sopor** [comment]
Hmm, i still have some weird sign here...
![image](https://user-images.githubusercontent.com/5789283/188756196-dc162b5f-eae0-4f39-a5e6-1881969f0cbd.png)

**Comment by iliajie** [comment]
This is universal sign for the `Shift` key.

**Comment by Sopor** [comment]
Is it a arrow pointing upwards? Same as on my physical keyboard?

Most of the time i use `OSK` and here it is written in text (you are using Alt, so why not use Shift instead of that tiny ridiculous arrow?) 😉

![image](https://user-images.githubusercontent.com/5789283/188760357-8cd651bf-a7f6-415c-aa1b-6c05e3e9c3a5.png)

**Comment by iliajie** [comment]
Well, I got your point. But _googling_ `shift key` always mention this `⇧` upwards arrow unicode character. Also, each mobile keyboard uses `⇧` character, so this is the reason why all across the UI we use `⇧` char rather than full `Shift` label. It's expected to be known, whereas `⌘` and `⌥` and `⌃` is not.
