### ISSUE TITLE
File manager - Type in the path

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1611]
When i use the File manager i sometimes have the path in my clipboard, but i can't find a way to type or paste in the path to get to the right directory.

Could it be possible to add an editable path row for easy directory change?

This will only support mouse click, i can't edit the path here:
![image](https://user-images.githubusercontent.com/5789283/181914046-c04a751e-92b4-45ab-97bb-f1ce26c64d41.png)

**Comment by iliajie** [comment]
Yes, it's already possible by clicking `Ctrl+L` (Mac users would use `Command+L`) or simply right-clicking on the breadcrumbs container.

**Comment by Sopor** [comment]
Great, but why not have a button? It is impossible to remember all the shortcut keys 😕

Right clicking? When i right click i only see Firefox's own menu.

**Comment by iliajie** [comment]
Right click on the breadcrumb area (grayish):

<img width="677" alt="image" src="https://user-images.githubusercontent.com/4426533/181937144-028ddad1-3a25-4532-a88b-ec2e93539d93.png">


Adding a button? Maybe,not sure if it will look and feel good.

There is a help button at the top, you can read throughout all hotkeys:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/4426533/181937177-7bba829e-a7b7-4512-aacd-1a82d73c044b.png">

**Comment by iliajie** [comment]
Alright, I ran few tests and I think you're right - having a button would be much more user friendly. I will add this and let you know when done.

**Comment by iliajie** [comment]
I think something like this will work just fine!

<img width="904" alt="image" src="https://user-images.githubusercontent.com/4426533/182027246-cb858862-6ff4-473f-a538-90e68d64cd30.png">

Try latest commit in version 19.99-RC1.

**Comment by Sopor** [comment]
Should the window that i type in close as soon as i move the mouse pointer outside the window?

When i press CTRL+L it will stay open until i move the mouse pointer over the window and away again.

It is a bit weird behavior in my opinion ...

![image](https://user-images.githubusercontent.com/5789283/182636277-82b215cf-ce32-41e6-8ff8-d27a939fc42c.png)

**Comment by iliajie** [comment]
> When i press CTRL+L it will stay open until i move the mouse pointer over the window and away again.

If you call it by the hotkey it's expected that afterwards, you type something in a popup and hit enter. Try using it for real - it's meant to be effective to have the work done.

**Comment by Sopor** [comment]
Most of the time i use the mouse. So, the issue is that if i open the path window i can't move the mouse outside the window 😥

**Comment by iliajie** [comment]
Oh, OMG! Okay, I will fix that! :-)

**Comment by iliajie** [comment]
> Most of the time i use the mouse. So, the issue is that if i open the path window i can't move the mouse outside the window 😥

Alright, this will be fixed on the next theme release. Thanks for reporting. Now I also agree that making a popover disappear on mouse out is annoying.
