### ISSUE TITLE
Error Upgrade Theme

### ISSUE THREAD

**Issue by PauloBoaventura** [webmin/authentic-theme#1614]
Unable to update the theme...
The system makes reference to a possible webmin update.

**_Version:_**
(installed version 19.93.1 (May/2022), latest stable 19.99)

**_System error information:_**

Installing this version of Authentic Theme 19.99
 requires the latest and/or possibly unreleased version of Webmin and Usermin to function properly. There may be incompatible changes, which may prevent the theme from working as designed. Unable to continue the update operation using the UI.

![unknown_2022 08 03-03 27](https://user-images.githubusercontent.com/18472254/182549942-beeb381e-ee6e-43ef-b624-615e9ae3a439.png)

**_Simple questions:_**

1 - What is the command to update only the theme?
 
2 - Is there any command to check the integrity of the webmin // virtualmin system?
(possibly before or after an update)

3 - Is it possible to generate a specific log of this execution?
(upgrade / integrity)

4 - How to perform an update of the webmin / virtualmin system only?

-----------------
**_comment:_**
_Streamlining time involved other issues that are not necessarily part of this repository. Although it may be co-related, in some way. I will update and make the necessary references._

**Comment by iliajie** [comment]
> 1 - What is the command to update only the theme?

There is no safe command to update it, unless you upgrade to Webmin 1.998 first. If you are on Virtualmin repos, you shouldn't update manually and wait for upcoming Webmin 1.999 to appear in Virtualmin repos. There is no exact ETA for that but it's happening soon!

>  Is there any command to check the integrity of the webmin // virtualmin system? (possibly before or after an update)

Package manager does that for you.

> 3 - Is it possible to generate a specific log of this execution? (upgrade / integrity)

Not sure.

> 4 - How to perform an update of the webmin / virtualmin system only?

Not sure what you're asking but if you are on Virtualmin repos, for any regular user I would advice to wait until we release Webmin 1.999 to Virtualmin repos! If you feel like you're capable to update Webmin outside of Virtualmin, go ahead and do it. Then you will be able to install theme 1.999 on Webmin 1.998.
