### ISSUE TITLE
Dashboard - Buttons to easy hide various stats from the dashboard

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1617]
When installing a new Webmin it is always a pain in the a** to find every off/hide button for the Recently logins (i don't think this can be turned off?), Disk usage, Network interface, Stats history and so on...

It would have been much easier if there was a hide button to easy hide it from the Dashboard.

Now i have to go here and go there to hide them all 🙁

Something like this:
![image](https://user-images.githubusercontent.com/5789283/188720544-11c14054-e0f2-43ca-be4b-17d85c1de2cf.png)

Or uncheck it and add the text **Hide**  😊

**Comment by iliajie** [comment]
Hello,

Is this the close button that you're looking for?

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/4426533/188726968-a96de31f-3689-4ce1-9c97-10af84be94f7.png">

**Comment by Sopor** [comment]
Yes, exactly 😊

**Comment by iliajie** [comment]
> Yes, exactly 😊

So, have you found it? 🙂 Or else what is an issue?

**Comment by Sopor** [comment]
Is that button on all of them?

**Comment by Sopor** [comment]
Yes, there was a button...

In that case there is no issue and i can close it.

**Comment by Sopor** [comment]
@iliajie If i hide the `Recent login`, where do i get it back again?

**Comment by iliajie** [comment]
Theme configuration page.

**Comment by Sopor** [comment]
@iliajie Hmm, i must be blind, 😎 because i can't find it 😔

**Comment by iliajie** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4426533/189437068-e770ce27-ab45-4d30-9213-798505291126.png">

**Comment by Sopor** [comment]
Ohh, i need to hide it first. That explains why i could find it.

But now to another question. How do i get it back?

![image](https://user-images.githubusercontent.com/5789283/189438265-3ea49802-3537-42ae-bda9-8afae569ebba.png)

Nothing happens when i click on it.

**Comment by iliajie** [comment]
> But now to another question. How do i get it back?

You need to hold Ctrl key to deselect accordions that you want to un-hide. This is standard multi-select functionality.

**Comment by Sopor** [comment]
That wasn't so easy to understand. The save button continues to be green. When i change other settings it will change to orange.

**Comment by iliajie** [comment]
> The save button continues to be green. When i change other settings it will change to orange.

That's a room for improvement. I'll have a look. Thanks.

**Comment by Sopor** [comment]
Couldn't you show these `Hidden accordions` in another way?

Maybe a checkbox: `Recent logins ▢` ?

**Comment by iliajie** [comment]
> That wasn't so easy to understand. The save button continues to be green. When i change other settings it will change to orange, so i know i need to press save.

Thanks, I will fix this on the next theme release.
