### ISSUE TITLE
`Return to previous page` doesn't work after NTP error

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1618]
I did a search for `ntp` (same thing happens if i go to `System time` from the left menu).
I then tried to change the ntp server, but i got this message:
`NTP time synchronization failed : Missing ntpdate and sntp commands` and a button `Return to previous page`, but when i press on the button nothing happens.

It seems that the button is not working when i get this error message.
![image](https://user-images.githubusercontent.com/5789283/188749755-cad8d777-a852-40a9-83c7-1287e0f59f76.png)

**Comment by iliajie** [comment]
Hello,

If you log in in a private tab, does it happen to work?

**Comment by Sopor** [comment]
What do you mean by a private tab?

**Comment by iliajie** [comment]
Incognito mode.

**Comment by Sopor** [comment]
I haven't tried that and now i have fixed the NTP error, so i can't test it in incognito mode.

I can of course recreate the error if it will help you?

**Comment by iliajie** [comment]
Yes, that would help if you could provide steps to reproduce it, as I here have a hard time reproducing it.

**Comment by Sopor** [comment]
I manage to get the NTP error back by uninstalling ntp, but the `Return to previous page` is working as it should and so do the back arrow button.

**Comment by Sopor** [comment]
I manage to recreate this issue in Cron Jobs.

If i `clear cache` in AT it seems to go away.

**Comment by iliajie** [comment]
What are the steps to reproduce it?

**Comment by Sopor** [comment]
Go to `Scheduled Cron Jobs` and click on `Create a new scheduler cron job`.

Now click on `Create` and you should see `Failed to save cron job : The user '' is not allowed to access cron`.

Now click on `Return to previous page` and the only thing that should happen is that the URL will change, but not the page.

When creating these step the failure is back again :(

**Comment by iliajie** [comment]
Did I do it right?

https://user-images.githubusercontent.com/4426533/190875362-318a36f9-8afe-4956-8395-822452a71bfa.mp4

It seems to work for me?

**Comment by Sopor** [comment]
Yes, you did it right, but as i explained it doesn't fail every time.

I did a test now on all my four `Webmin` and they all worked.

I'm running Firefox 104.0.2

**Comment by iliajie** [comment]
Well, it can be tricky. Theme is complex.

**Comment by Sopor** [comment]
Here is a video:

https://user-images.githubusercontent.com/5789283/191654213-5745c06e-ce0d-45a2-9626-f2eec833a98e.mp4

**Comment by iliajie** [comment]
Have a look at this:


https://user-images.githubusercontent.com/4426533/191719165-fba0a3cb-270c-4dd9-9c72-d2f03efa6fad.mp4

Do you have any errors on the browser console when this bug happens? If you do, can you click a triangle button to unfold the stack and see where it fails exactly?

Which browser are you using? Does this happen in incognito tab (where all extensions are disabled) or in another browser?

**Comment by Sopor** [comment]
I can't see any errors, but i will keep my eyes open.

I have tried in incognito mode a few times, but those times i have tried it has worked.

I'm running Firefox.
