### ISSUE TITLE
Version 20.01:2 available, but not showing up when checking for an update

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1619]
I'm running AT 20.01 and when i check for an update it will tell (installed version 20.01) and nothing more.

If i then choose `Install latest development version` it seems that i get version `20.01:2` installed.

Why isn't the version `20.01:2` showing up when i check for an update?

**Comment by iliajie** [comment]
> Why isn't the version 20.01:2 showing up when i check for an update?

Because 20.01:2 is a build version and not a tagged version.

**Comment by Sopor** [comment]
It is not easy to understand all these versions 😕
