### ISSUE TITLE
`systemd timers` in Authentic Theme

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1623]
I'm running Let's Encrypt and it seems that they have made it easier to install.

Now you don't need to add anything to the Cron jobs. Instead it will be added here:
```
$ systemctl list-timers
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
Mon 2022-09-19 06:14:00 CEST 5h 31min left n/a                          n/a          snap.certbot.renew.timer     snap.certbot.renew.service
```
But where can i find this in Authentic Theme without running `systemctl list-timers` and how can i add and edit the list from AT?

**Comment by iliajie** [comment]
> But where can i find this in Authentic Theme without running `systemctl list-timers` and how can i add and edit the list from AT?

This is not Authentic Theme question. Timers should also be listed in **Bootup and Shutdown** module though.

By the way, if you use Webmin or Virtualmin to setup to request certificates for virtual servers, you should never setup manually any custom cron jobs, as Virtualmin does it automatically.

**Comment by Sopor** [comment]
> By the way, if you use Webmin or Virtualmin to setup to request certificates for virtual servers, you should never setup manually any custom cron jobs, as Virtualmin does it automatically.

It is impossible to know what every application do. I haven't seen any setup in Webmin for a certificates.

So, there is no easy way to list these timers in Webmin?
If i run:
```
$ sudo systemctl list-timers
NEXT                         LEFT          LAST                         PASSED        UNIT                         ACTIVATES
Tue 2022-09-20 19:09:00 CEST 5min left     Tue 2022-09-20 18:39:03 CEST 24min ago     phpsessionclean.timer        phpsessionclean.service
Tue 2022-09-20 22:40:23 CEST 3h 36min left Mon 2022-09-19 22:40:24 CEST 20h ago       systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Wed 2022-09-21 00:00:00 CEST 4h 56min left Tue 2022-09-20 00:00:02 CEST 19h ago       logrotate.timer              logrotate.service
Wed 2022-09-21 06:14:00 CEST 11h left      Tue 2022-09-20 16:11:02 CEST 2h 52min ago  snap.certbot.renew.timer     snap.certbot.renew.service
Mon 2022-09-26 01:38:42 CEST 5 days left   Mon 2022-09-19 00:45:13 CEST 1 day 18h ago fstrim.timer                 fstrim.service

5 timers listed.
```
I did try the filter but it wasn't that easy. I wrote `timer` but it will not show all timer there 😕
![image](https://user-images.githubusercontent.com/5789283/191329361-492cd935-db1f-47a4-92f5-056a22267127.png)


So, there isn't any easy way to list the timers without running the `systemctl list-timers`?

**Comment by iliajie** [comment]
Please, let's make it right -- you should submit this ticket to [webmin/webmin](https://github.com/webmin/webmin) repo, by simply copying and pasting your last message.
