### ISSUE TITLE
System supports bootup/shutdown messages

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1624]
Shouldn't `System supports bootup/shutdown messages` have a default settings? As you can see either `No` or `Yes` is selected

![image](https://user-images.githubusercontent.com/5789283/192801191-f08a1dd3-30ee-4bea-b407-a2f7521387a1.png)

Btw, how do i know if my system do support bootup/shutdown messages? Where will these messages show up?

**Comment by iliajie** [comment]
It should be set to "No" on contemporary systems. I talked to Jamie and we agreed that amount of options should be reduced. Also options should be made conditional depending on the system, as showing all options unconditional is confusing (i.e. showing FreeBSD related options on Linux systems).

**Comment by jcameron** [comment]
I deleted this and a bunch of other redundant config options..
