### ISSUE TITLE
File Manager - Add a page selector at the top

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1625]
I wondering if you could add this page selector at the top of the page in the file manager?
![image](https://user-images.githubusercontent.com/5789283/193699917-55fe3746-5b4f-4c70-a0bf-96b3272a3dc7.png)

When browsing between the pages i always have to go to the bottom of the page to change page even if i'm at the top of the page.

That is why it would have been nice to have a page selector at the top too 😊

**Comment by jcameron** [comment]
@iliajie I think this is configured by the theme?

**Comment by iliajie** [comment]
Hello,

> I wondering if you could add this page selector at the top of the page in the file manager?

No, it won't be possible to add this, as it's completely impractical. Not only you don't need those pagination buttons to be visible directly to switch between pages, as you can do it using left and right arrow keys (using keyboard). Also, you should consider using `Show items` select to make pagination buttons always visible on the page without scrolling:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/4426533/194549455-e4cb33a3-8550-4bc5-b654-f178679bfac3.png">

**Comment by Sopor** [comment]
I have `Enable tree view` set to No because i really hate Windows File Explorer look. I use Total Commander that don't have that ridiculous tree view look.

Then i use the mouse a lot and i don't like to swap between keyboard and the mouse only to browse some files.

Nothing more to do about it then 😥
