### ISSUE TITLE
Always asks to restart

### ISSUE THREAD

**Issue by jim-j** [webmin/authentic-theme#1631]
Updated to 20.02-2 yesterday. Keep getting messag e"It is detected that the Webmin web-server daemon was not restarted correctly on the last package upgrade....Manually restart using /etc/webmin/restart command". Restart works, but I keep getting this message every time I login to webmin. Don't know how to fix this. On 
Redhat Enterprise Linux 6
Linux 2.6.32-754.35.1.el6.x86_64 on x86_64
Authentic theme: 20.02-2
Intel(R) Xeon(R) CPU E5645 @ 2.40GHz, 12 cores

**Comment by jcameron** [comment]
@iliajie any suggestions as our resident systemd expert?

**Comment by iliajie** [comment]
I think the user installed Authentic Theme alone (ignoring a warning message) without installing Webmin itself.
