### ISSUE TITLE
webmin: networking - fail2ban - Jail Status: Table cells 

### ISSUE THREAD

**Issue by NicodemusFLT** [webmin/authentic-theme#1632]
Webmin:  networking-> fail2ban intrusion detector --> jail status and actions 

the table cells do not fit, if for a jail another systemjournal is used than systemd, for example here for proftpd the old log file is used and as you can see, the log name with path is then shown that is used by a new inserted cell, so all others are moved to the right. You can see a "-" on the far right that is disordered because of this. "97" would be correct in the total banned column.

![image](https://user-images.githubusercontent.com/111750567/203578085-5a415c2c-828b-4061-bc1c-ed59bb407145.png)

**Comment by iliajie** [comment]
Hello,

Webmin version?

**Comment by iliajie** [comment]
What is the output of `fail2ban-client status` command?

**Comment by NicodemusFLT** [comment]
[root@x4a ~]# fail2ban-client status
Status
|- Number of jail:	9
`- Jail list:	blacklist, dovecot, pam-generic, postfix, postfix-sasl, proftpd, sshd, webmin-auth, xinetd-fail

[root@x4a ~]#

**Comment by iliajie** [comment]
Also, what is the outputs of:

```
fail2ban-client status proftpd
fail2ban-client status sshd
```

**Comment by NicodemusFLT** [comment]
[root@x4a ~]# fail2ban-client status proftpd
Status for the jail: proftpd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	591
|  `- File list:	/var/log/proftpd/proftpd.log
`- Actions
   |- Currently banned:	0
   |- Total banned:	101
   `- Banned IP list:	

[root@x4a ~]#
[root@x4a ~]# fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- Journal matches:	_SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	

[root@x4a ~]#

**Comment by NicodemusFLT** [comment]
Looks good to me ... thanks

![image](https://user-images.githubusercontent.com/111750567/203573249-8eb3f3f3-9f5a-4ae5-af1d-4ad245ad0439.png)
