### ISSUE TITLE
Upgrade Webmin - E: Unsupported file...

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1633]
I updated Webmin through the Authentic theme and got this error message:

E: Unsupported file... (read whole message in the picture)

![image](https://user-images.githubusercontent.com/5789283/204160784-54924131-ec7d-48d7-a377-44321dbcdc53.png)

Should i ignore it or is it important?

The upgrade process finished as it should.

**Comment by iliajie** [comment]
Hello,

It looks fine to me.

**Comment by jcameron** [comment]
This is harmless, but we'll fix it in the next release.
