### ISSUE TITLE
Terminal not working anymore ?

### ISSUE THREAD

**Issue by ochbob** [webmin/authentic-theme#1635]
Hello,

Terminal is not working anymore ?
I'm running the last webmin 2.010  / authentic theme 20.11 (Debian 11)

I have the "connecting" message then an error appear: "please check in the terminal module"
I went to the terminal module, but nothing, just a black screen.

It works great few previous version.

Any ideas ?

Thank you.

**Comment by jcameron** [comment]
Does anything get logged to one of the `/tmp/.webmin/ws-*` files?

**Comment by iliajie** [comment]
> I have the "connecting" message then an error appear: "please check in the terminal module"
> I went to the terminal module, but nothing, just a black screen.

You should try [this new](https://ilia.engineer/webmin_2.010-3_all.deb) development version of Webmin that fixes various Terminal related bugs.

**Comment by ochbob** [comment]
> Does anything get logged to one of the `/tmp/.webmin/ws-*` files?

Nothing :/
Only a .theme__webmin_redirected_

I will try the dev version, thank you.

**Comment by ochbob** [comment]
I upgrade from repo with the script in /usr/share/webmin (2.01012032207 )
I have now a clear error message: 

"The Perl module Net::WebSocket::Server is missing, but can be [installed automatically]module."

**Comment by iliajie** [comment]
> I upgrade from repo with the script in /usr/share/webmin (2.01012032207 )

Install the devel package suggested earlier or make sure that these dependencies are installed on your Debian system:

```
apt-get install libnet-ssleay-perl libauthen-pam-perl libpam-runtime libio-pty-perl libdigest-sha-perl libdigest-md5-perl
```

**Comment by ochbob** [comment]
All dependencies are already well installed.

I will try your package.

**Comment by ochbob** [comment]
Still the same :/

**Comment by iliajie** [comment]
It would help a lot if I could have an access to this server. If not, you should figure out which dependencies are failing.

What is the output of:

```
perl -e "use lib ('/usr/share/webmin/vendor_perl'); use Net::WebSocket::Server;"
```

Also, what is the content of Webmin's `miniserv.conf` and `config` files?

**Comment by ochbob** [comment]
It's working now :)
Like the error said, I haven't installed the PERL Module/Build/Tiny to compile a module.
I installed it:

`cpan Module::Build:Tiny`

then I go back to Terminal module in Webmin to installed the recommended module Net::WebSocket::Server and an another one which thrown me the compilation error at the first time without the Module::Build::Tiny (I dont remember the name of it, sorry)

**Comment by swelljoe** [comment]
You should not need to install anything! The current package is supposed to have the necessary modules bundled.

**Comment by iliajie** [comment]
> Oh, didn't know that.
> If you need more information about my configuration, don't hesitate.

Please give it a try with this [devel package](https://ilia.engineer/webmin_2.010-10_all.deb). I'm pretty sure it should fix a problem for you.

**Comment by ochbob** [comment]
Hello @iliajie 
About this, i'm using a reverse proxy (Haproxy) to access webmin and from outside it's not working.

All request goes to haproxy on SSL port (443)
I'm connecting to webmin by https://webmin.server.com then if webmin is in my url redirect haproxy redirect traffic to localhost:10000 internally.
It's working great, but I always have to rewrite manually my url, because haproxy redirect me to https://webmin.server.com:10000
So I add a redirect rule:
http-response replace-value Location ^http://webmin.leetnetwork.net:10000/$ https://webmin.leetnetwork.net/

to simply remove the :10000 to the URL.

But when i'm accesing webmin from outside my network, terminal is not working, everything works fine when I'm connecting locally (192.168.x.x:10000)

Do you have an idea how to bypass this issue when i'm outside ?
No particular option in the Web Server Option.

(Maybe i should open another issue ?)

Thank you !

**Comment by ochbob** [comment]
Il will check this part, I think this is the issue, you right.
ws is listening on 555 or 570 port ?

**Comment by iliajie** [comment]
> ws is listening on 555 or 570 port ?

The port is picked dynamically, starting from 555 and going up, depending on how many terminal instances would be started on your system.

**Comment by ochbob** [comment]
Ok, I see, that's why I have seen a 570 port listening after lauching terminal.
I dont know if I can configure haproxy without specifiying a port for the web service.
I will try, thank you.

**Comment by iliajie** [comment]
Those ports are local connections, and they have nothing to do with your proxy. Although, depending on the proxy configuration, you may need to explicitly proxy `wss` protocol.

For instance, in case of a balancer in Apache, you don't need to specifically proxy websockets as it happens automatically. Perhaps, there is something familiar available in HAProxy..

**Comment by ochbob** [comment]
@iliajie 
I dig this issue a little bit more.
With Safari debug mode, I can see this error:

[blocked] The page at https://webmin.server.net/sysinfo.cgi?xnavigation=1 was not allowed to run insecure content from ws://webmin.leetnetwork.net/xterm/ws-572.

I added to my Webmin Haproxy backend:

 `http-response set-header content-security-policy upgrade-insecure-requests`

Now everything works great from outside.

**Comment by iliajie** [comment]
The better solution would be is to enable SSL on Webmin side!

**Comment by ochbob** [comment]
I like the idea to have only one place (into Haproxy) to keep up to date my certificate, HAproxy is handling the SSL part.
If i enable SSL on webmin side, I have to put my certifcate in webmin too, right ?
I will have:
Client> -----SSL---- Haproxy> -----SSL---- >Webmin
Right now I have:
Client >-----SSL---- Haproxy> ---NO_SSL--- >Webmin
All advices are good, as i'm not an expert ˆˆ
