### ISSUE TITLE
Virtualmin Scheduled Backup "Backup destinations" path field is not visible by default

### ISSUE THREAD

**Issue by SamSirry** [webmin/authentic-theme#1638]
When scheduling a backup in Virtualmin (at /virtual-server/backup_form.cgi), the textbox to enter the backup file path is not visible by default, even though the first option `File under virtualmin-backup/` is selected by default.

![image](https://user-images.githubusercontent.com/30126053/211624030-38a8d10f-0354-49b5-ac41-03ccfac199ea.png)

Selecting a different `Backup destinations` then selecting the first one again makes the textbox visible.

![image](https://user-images.githubusercontent.com/30126053/211624531-5c3f1239-a43b-4aac-8140-c7b8e4dcc98d.png)

**Comment by iliajie** [comment]
Hello,

Thank you for reporting this.

Do you see this when logged in as master administrator or virtual server owner?

**Comment by SamSirry** [comment]
I just attempted to run the scheduled backup manually. I clicked the `Backup` action, and the `Backup destinations` is now appearing twice.
![image](https://user-images.githubusercontent.com/30126053/211625345-c73b3582-2742-41ce-9292-b4bba73eb4b3.png)


![image](https://user-images.githubusercontent.com/30126053/211625107-ce7f4d70-fca5-44a0-ba6c-5fc0b7faa52b.png)

**Comment by SamSirry** [comment]
> Do you see this when logged in as master administrator or virtual server owner?

In both cases the same :)

**Comment by iliajie** [comment]
The actual bug is on Virtualmin side. The fix is here https://github.com/virtualmin/virtualmin-gpl/commit/09ae784ed7a78debd00c6e5189f46d30fb3a1cff.

Although, @jcameron, what is `oneoff` option does?

**Comment by SamSirry** [comment]
Probably one-off is when the user is doing a manual backup that is one shot and then they're done. This is in contrast to running a scheduled backup manually, or to creating a new schedule.

**Comment by jcameron** [comment]
Yes, the `oneoff` parameter is for doing a one-off run of a scheduled backup.
