### ISSUE TITLE
Night mode - difficult distinguishing buttons/fields/etc from their surroundings

### ISSUE THREAD

**Issue by koalasinspace** [webmin/authentic-theme#1639]
Hope this isn't easy to change setting I missed somewhere- when using dark mode it's almost impossible for me to tell where radio buttons are and other fields drops downs etc are similarly hard to distinguish without getting pretty close to my display or not using night mode at all (which I've had to do a lot sadly as I completely miss some things and don't notice until after the fact).

Thanks

**Comment by iliajie** [comment]
Hello,

Thanks for your report. I was planning to add more improvements to the dark mode, particularly improving readability.

Although, could you name a service (YouTube or GitHub, maybe) when used with a dark theme, and which looks good to you on your monitor?

**Comment by iliajie** [comment]
Hello,

This issue along side with many other were fixed for the dark palette!

Thanks for the heads up and sorry for the delay!
