### ISSUE TITLE
Smooth/eased scrolling in the left sidebar

### ISSUE THREAD

**Issue by robertthemay** [webmin/authentic-theme#1640]
Maybe I am blind, but Is there an option to disable the smooth scrolling effect in the sidebar? For now I have downgraded to 20.11. Thanks.

**Comment by iliajie** [comment]
Hello,

Can you describe the problem more depictive, i.e. provide a screencast maybe? What is wrong and what are you trying to achive?

**Comment by robertthemay** [comment]
https://user-images.githubusercontent.com/98313962/212965721-e686a12c-fece-4886-82ef-0849a4ead87e.mp4
Here in version 20.11.1, I am scrolling down once with mouse, and up once with mouse a few times on the sidebar. There is a 500ms(estimate) delay between the between the time I have scrolled, and the time it takes for the scrolling animation to finish. It feels laggy.

https://user-images.githubusercontent.com/98313962/212966433-27430fb4-3355-4eeb-8b50-bc24dec5816f.mp4
Version 20.11 - I am doing exactly the same. It is much more snappy and responsive.

**Comment by iliajie** [comment]
Alright, I see. Try installing the latest theme 20.11.1:5 using theme configuration page and see if it fixes the problem for you.

**Comment by robertthemay** [comment]
It is fixed. You are amazing, thank you.

**Comment by iliajie** [comment]
You're very welcome.
