### ISSUE TITLE
read mail module

### ISSUE THREAD

**Issue by truckertomnz** [webmin/authentic-theme#1641]
won't display buttons at the bottom of email, all other themes do
this has occurred after the last update

**Comment by truckertomnz** [comment]
2.013 has only just become available for me but the issue is the same.
you say buttons can't be displayed top and bottom together but until 2.012 they were
thx, I'll use a different theme

**Comment by iliajie** [comment]
> 2.013 has only just become available for me but the issue is the same.

I am surprised to hear this. Can you provide the screenshot of how it's broken for you?

If you want forcefully to display buttons at the bottom only you should go to Read User Mail module configuration and set **Show buttons at top for** to **Never**.
