### ISSUE TITLE
Dynamic DNS Client module PERL error

### ISSUE THREAD

**Issue by qwrty-ftw** [webmin/authentic-theme#1643]
Hello,

Dynamic DNS Client module throw a PERL error when going in Daemon settings: 

![image](https://user-images.githubusercontent.com/16723954/214803192-5ba4fff4-e618-4e0d-9bf6-a6fa8845d558.png)
It doesn't seem blocking.

Do you reproduce or it's only on my side ? (maybe it's a module issue ?)
Thank you :)

**Comment by iliajie** [comment]
Hello,

This should be fixed by original module developer, which calls `ui_form_end` incorrectly.

**Comment by qwrty-ftw** [comment]
So not on your side, thank you for the feedback, I close the issue :)
