### ISSUE TITLE
background black level too black in switch-mins

### ISSUE THREAD

**Issue by verne-work** [webmin/authentic-theme#1644]
Perhaps my monitors need adjusting -- my secondary monitor does have the unselected item (Webmin/Virtualmin) visible while on my primary monitor its just too dark and displays as a big black rectangle -- the words Webmin/VirtualMin are not visible when using the current 11,11,11 RGB setting for switch-mins.  I tested my proposed change using the custom CSS settings in Theme Config -- Theme Extensions.  I found this background setting first and tried 75,75,75 which worked, so did not explore any ways to adjust the 'greyed out' font text color or dimness -- its possible that route, if any adjustments are accepted, could be a better way or easier way to overcome my problem.  I bet almost anything there is a source code CSS file better suited for editing -- one that is used to build this bundle.min.css file.

in bundle.min.css I find this fragment:

`.switch-mins{text-align:center;color:#c7d2e6;border-radius:0;background-color:rgba(11,11,11,.9)}`

I propose replacing 11,11,11 with 75,75,75

See attached cell phone photos of my substandard monitor --- here it is with the updated CSS:

![webmin-75-75-75--20230213_175819-smaller](https://user-images.githubusercontent.com/95433173/218594787-fa4055f0-7850-42e1-b204-e9cd3b39ad5e.jpg)

and below is the original CSS -- way too dark:

![webmin-11-11-11--20230213_175737-smaller](https://user-images.githubusercontent.com/95433173/218594832-8b51582a-d4c1-4953-bf3b-f2e4639d6417.jpg)

on my secondary monitor the original CSS, while still quite dark, is visible -- of course with my edit its much more visible.

**Comment by verne-work** [comment]
and I should mention -- as I click around some more while exploring the Authentic Theme, I find additional menu/tab items that appear too dark as well, so its possible other CSS settings will need adjusting.

**Comment by iliajie** [comment]
Hello! Thanks for the heads up!

Well, I agree that the contrast of the disabled switch in navigation menu can be improved. This is done on the latest commit.

Although, I can assure you that the colors/contrast/brightness levels on your monitor is way off.

**Comment by iliajie** [comment]
And the CSS rule you should have used (which I've used on the latest commit) is this:

```css
.switch-mins label
{
    color: #f3f3f3;
    opacity: .33;
}
```

**Comment by verne-work** [comment]
thanks .... and of course the LABEL construct is much better ... of course I have to go off and read a lot about CSS to fully understand it all   :-)

any thoughts on the cleanest way to 'fix' the right-side-tabs flyout -- it appears to suffer as well from this issue of a darker part upon another darker part --- looking quickly I cannot see what CSS item controls those colors.

**Comment by iliajie** [comment]
> any thoughts on the cleanest way to 'fix' the right-side-tabs flyout -- it appears to suffer as well from this issue of a darker part upon another darker part

You're right. I have missed it. Fixed on the last commit.
