### ISSUE TITLE
Undefined subroutine &WebminCore::parse_accepted_language called at /usr/share/webmin/authentic-theme/authentic-init.pl line 831.

### ISSUE THREAD

**Issue by alanmels** [webmin/authentic-theme#1645]
Usually our script that installs a fresh Webmin/Virtualmin and executes:

```
yes | /usr/share/webmin/authentic-theme/theme-update.sh 
```

works fine, but this time attempting to login to Webmin via UI is giving:

```
HTTP/1.0 500 Perl execution failed Server: MiniServ/2.013 Date: Tue, 14 Feb 2023 20:35:42 GMT Content-type: text/html; Charset=utf-8 Connection: close
ERROR — PERL EXECUTION FAILED
Undefined subroutine &WebminCore::parse_accepted_language called at /usr/share/webmin/authentic-theme/authentic-init.pl line 831.
```

The `/etc/webmin/miniserv.conf` and `/etc/webmin/config` files have `preroot=authentic-theme` and `theme=authentic-theme` respectively.

**Comment by alanmels** [comment]
I had to downgrade to https://github.com/webmin/authentic-theme/archive/refs/tags/20.13.tar.gz as apparently the last dev branch doesn't work with Webmin core.

**Comment by iliajie** [comment]
Hello.

> Usually our script that installs a fresh Webmin/Virtualmin and executes:

Never use this on the production system! Use package manager to install updates. Authentic Theme is distributed with Webmin and may have it as a dependency!

> Undefined subroutine &WebminCore::parse_accepted_language called at /usr/share/webmin/authentic-theme/authentic-init.pl line 831.

Unless `/etc/webmin/restart-by-force-kill` works, you need to downgrade the theme to the version that is distributed with Webmin 2.013. This can be done by simply reinstalling current Webmin version.

**Comment by swelljoe** [comment]
Software installed from git is expected to be broken, sometimes. Use the stable version in the Webmin package, if you want it to always work.
