### ISSUE TITLE
How to disable the Virtualmin logo shown during logging in?

### ISSUE THREAD

**Issue by AlexShapka** [webmin/authentic-theme#1646]
When logging in the following logo is displayed: 

![Screenshot 2023-02-23 at 2 48 12 AM](https://user-images.githubusercontent.com/9372724/220860707-1354ab6f-8f1b-4643-891c-4d71ee217707.png)

Is it possible to disable or replace it?

**Comment by jcameron** [comment]
@iliajie this sounds like a theme question ...

**Comment by iliajie** [comment]
> Is it possible to disable it?

Yes, you can disable it by using browser's console and entering two following commands:

```js
settings_embed_product_branding_privileged = false;
theme.config.save();
```

> Is it possible to replace it?

Yes, you could place custom _brand_ content (based on the standard content, which can be found in the theme root under `images/brand` directory) to `/etc/webmin/authentic-theme/brand`.

**Comment by AlexShapka** [comment]
Thanks, that made the trick.
