### ISSUE TITLE
Xterm ssh terminal it's not connecting

### ISSUE THREAD

**Issue by luciancurteanu** [webmin/authentic-theme#1647]
When I try to use the webmin ssh terminal it's only showing CONNECTING...

**Comment by iliajie** [comment]
Hello,

What is getting logged to `/tmp/.webmin` when you're trying to connect?

**Comment by luciancurteanu** [comment]
Thanks for reaching out,

Running shell '/bin/bash -bash' with pid 22701
listening on port 557
timeout waiting for connection at /usr/libexec/webmin/xterm/shellserver.pl line 103.

**Comment by iliajie** [comment]
Is Webmin running behind proxy?

**Comment by luciancurteanu** [comment]
nope

**Comment by iliajie** [comment]
Not sure then. What is Webmin version you're running? Which distro and version is this? Does it work if you switch to the old Framed Theme?

**Comment by luciancurteanu** [comment]
Yes it's working with Framed Theme

**Comment by iliajie** [comment]
Does it work in Authentic if you use stand-alone mode, i.e. `Tools -> Terminal` rather than dropdown?

Also, did you try using incognito mode? Did you try using the other browser which doesn't have extensions enabled? Did you try force-reloading browser's cache by hitting `Ctrl+Shift+R`?

**Comment by luciancurteanu** [comment]
No. I get this error: Failed loading terminal : Websocked connection error

**Comment by iliajie** [comment]
What error exactly is thrown to browser's console?

**Comment by luciancurteanu** [comment]
WebSocket connection to 'wss://example.com/xterm/ws-556' failed:

**Comment by iliajie** [comment]
Sorry, this is not enough of details to understand what's wrong!

What OS and version this is? What browser and version are you using?

**Comment by luciancurteanu** [comment]
OS : CentOS Linux 7.9.2009
Kernel : Linux 3.10.0-1160.83.1.el7.x86_64
Browser : Chrome 110.0.5481.178

**Comment by iliajie** [comment]
Can you share your `/etc/webmin/miniserv.conf` and `/etc/webmin/config` files in a zip file attached to this threat?

**Comment by iliajie** [comment]
Plus `/etc/webmin/xterm/config` file.

**Comment by luciancurteanu** [comment]
**Config file**

ld_env=LD_LIBRARY_PATH
passwd_cindex=2
passwd_uindex=0
find_pid_command=ps auwwwx | grep NAME | grep -v grep | awk '{ print $2 }'
path=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
passwd_pindex=1
passwd_mindex=4
passwd_file=/etc/shadow
tempdelete_days=7
by_view=0
os_type=redhat-linux
os_version=15.9
real_os_type=CentOS Linux
real_os_version=7.9.2009
lang=en
log=1
referers_none=1
md5pass=0
theme=authentic-theme
product=webmin
referers=example.com
noremember=
webprefix=
realname=
passapi=0

**Miniserv file**

port=1986
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
ssl=1
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
listen=1986
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=10600
syslog=1
ipv6=1
session=1
premodules=WebminCore
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/miniserv.pem
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=authentic-theme
passdelay=1
login_script=/etc/webmin/login.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
failed_script=/etc/webmin/failed.pl
trust_real_ip=1
error_handler_403=403.cgi
error_handler_404=404.cgi
error_handler_401=401.cgi
nolog=\/stats\.cgi\?xhr\-stats\=general
pam_end=
pam_conv=
blockuser_time=10600
blocklock=
session_ip=
blockuser_failures=5
no_pam=0
logouttime=
utmp=
root=/usr/libexec/webmin
mimetypes=/usr/libexec/webmin/mime.types
server=MiniServ/2.013
websockets_/xterm/ws-555=host=127.0.0.1 port=555 wspath=/ user=root time=1677859390

**Comment by iliajie** [comment]
You should go to browser's console, open _Network_ tab and check _WS_ sub-tab, then try to re-connect and then check what is happening with _WS_ connection exactly. Your configs work for me.

Another suggestion would be to force restart Webmin by running `/etc/webmin/restart-by-force-kill` command.

**Comment by luciancurteanu** [comment]
I just restart the server, same thing
