### ISSUE TITLE
Webmin menu on iOS 16.4

### ISSUE THREAD

**Issue by Whistley1** [webmin/authentic-theme#1652]
Since upgrading my iPad to iOS 16.4, the webmin menu does not stay on screen to enable user to select menu items.  Webmin interface works ok on PC.

**Comment by iliajie** [comment]
Hello,

This is a [known issue](https://github.com/webmin/webmin/issues/1870#issuecomment-1492106224). I'm working on resolving this.

**Comment by iliajie** [comment]
Fixed. Details [here](https://github.com/webmin/webmin/issues/1870#issuecomment-1492681680).
