### ISSUE TITLE
Recent logins don't show my actual IP address

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1653]
I don't know if this behaviour is normal or not, but it do make the user (or at least me) a bit confused.

I have been logged to this Webmin quite some time and after a planned power outage i got a new IP address, but in the `Recent login` it will still show my old IP address that i haven't been used for several weeks (if not month).

Here are current login sessions showing my old IP address (wrong IP):

![image](https://github.com/webmin/authentic-theme/assets/5789283/d022436e-4454-4335-ba99-7e5d459f6932)

After logging out and in again, it will now show my current IP address (correct IP):

![image](https://github.com/webmin/authentic-theme/assets/5789283/23fb7195-3a25-4cd0-9d67-8442024699e3)

Red=My session before i logged out that show my old IP address.
Green=My new session after i logged out and in again.
You can even see both session now.

So, why will it not update the IP address in the `Recent logins` and `current login sessions` when i get a new IP address?

`Last active at` seems to update, but not the IP address, but as i mentioned before, this behaviour may be correct?

Windows 10
Firefox 113.0.2 (64-bit)
Webmin 2.021
AT 20.21

**Comment by jcameron** [comment]
This is actually a Webmin bug - if your IP changes, we don't update it in the session database. This will be fixed in the next release..
