### ISSUE TITLE
Stylesheet overrides "size" setting for &theme_ui_select when it is multiselect

### ISSUE THREAD

**Issue by klugerama** [webmin/authentic-theme#1654]
The generated `select` objects _do_ have the `size` property, but the stylesheet is enforcing both a `min-height` (of "120") and a `max-height` (of "28").

Supplying a `class` or `style` as a parameter in the call to `&ui_select` doesn't do anything either, presumably because both of those attributes are overridden after rendering. Mitigating this problem therefore requires adding additional `$(document).ready()` JS code.

Notice also that the value of `min-height` is _greater_ than that for `max-height`, meaning that both values must be overridden to predictably  get the desired result.

**Comment by iliajie** [comment]
Hello,

It sounds like one of the old bugs. I will have a look and update this ticket with progress.

Thanks!

**Comment by iliajie** [comment]
Alright, it was just fixed on the latest commit.
