### ISSUE TITLE
Night mode won't stick on this one VPS

### ISSUE THREAD

**Issue by julioasoares** [webmin/authentic-theme#1655]
|  SYSTEM INFORMATION||
|------------------------------------|------------------------------------|
| OS type and version | Ubuntu Linux 22.04.2 |
| Webmin version | 2.021 |
| Authentic Theme version | 20.21 |
| Processor information | AMD EPYC 7282 16-Core Processor, 4 cores |

I have this one VPS instance where _night mode_ would not ‘survive’ once we navigate or refresh pages. Additionaly the graphics on _System Information_ show blurred and without colors in dark mode.

Toggling night/day mode works inconsistently (don’t always toggles) both with shortcut or icons and navigating to any tab or page will turn night mode off but leave the blurred graphics behind. If we refresh the page the graphics would come back normal (in day mode only).

I have 3 other VPS instances working fine. I know it probably means nothing but the only difference is that the other VPSs are all Intel Xeon VMs.

This is how it looks when "normal"
![image](https://github.com/webmin/authentic-theme/assets/12709450/51f5a82b-6f92-4ec3-93aa-5c3b568f36f1)

Then if toggling to night mode...
![image](https://github.com/webmin/authentic-theme/assets/12709450/29f30861-f5aa-419b-9c63-555ee55e3eac)

Toggling back...
![image](https://github.com/webmin/authentic-theme/assets/12709450/1ce425fe-95e0-4c6d-ba96-ddcf1febdb46)

If I refresh the page anytime it goes day mode with the normal (sharp and colored) graphics.

Thenak you

**Comment by iliajie** [comment]
Hello, Julio!

If you open browser's console and toggle day/night mode -- do you see any errors? Also, if you try another browser (or incognito tab), with all extensions disabled -- does it change anything? Or it just works fine in the same browser but for other servers?

**Comment by julioasoares** [comment]
It works just fine for the other sites on the same browser.
It behaves the same on edge or on Chrome with incognito window

**Comment by iliajie** [comment]
Excellent! Could you now open browser console and see what errors do you get on switching dark/light modes?

**Comment by julioasoares** [comment]
[panel.demimot.com-1686650757375.log](https://github.com/webmin/authentic-theme/files/11733610/panel.demimot.com-1686650757375.log)
[panel.demimot.com-1686650781474.log](https://github.com/webmin/authentic-theme/files/11733612/panel.demimot.com-1686650781474.log)
[panel.demimot.com-1686650792118.log](https://github.com/webmin/authentic-theme/files/11733614/panel.demimot.com-1686650792118.log)
[panel.demimot.com-1686650801679.log](https://github.com/webmin/authentic-theme/files/11733615/panel.demimot.com-1686650801679.log)

**Comment by iliajie** [comment]
Is this instance in Cloudflare or behind other proxy? If so, could you tell more about DNS and proxy configuration for the instance that's having an issue?

**Comment by iliajie** [comment]
Please follow this guide to setup Apache gateway for Webmin:

https://webmin.com/faq/#can-i-run-webmin-or-usermin-behind-reverse-proxy

**Comment by julioasoares** [comment]
It gets me a "502 bad gateway" error.

**Comment by iliajie** [comment]
This is not the theme issue!

> I adjusted certificate paths, server name, etc. to suit my setup but all I get is a "502 bad gateway" error.

This error indicates that Apache proxy did not receive a valid response from the Webmin backend server.
