### ISSUE TITLE
Xterm webgl renderer?

### ISSUE THREAD

**Issue by robertthemay** [webmin/authentic-theme#1656]
Would it be possible to include the webgl addon for xterm? - https://www.jsdelivr.com/package/npm/xterm-addon-webgl

I'm getting 2fps when scrolling in a relatively large terminal window when xterm is set to use the basic DOM renderer
https://github.com/webmin/authentic-theme/assets/98313962/90b89ae0-4250-4ab0-a463-524b8c38c333

Also, the ability to enable and adjust the `smoothScrollDuration` option of `Terminal`(xterm.js) would be helpful - but that is just a personal preference.

**Comment by iliajie** [comment]
Hello,

Sounds like a good improvement. I will take a closer look and update this ticket with progress ..

**Comment by iliajie** [comment]
This was implemented for inclusion to the next Webmin release. You can download and install nightly Webmin built to give it a try right now.

**Comment by robertthemay** [comment]
It's a huge improvement! It feels much better working in the terminal now - everything is super responsive. Thank you.

**Comment by iliajie** [comment]
> It's a huge improvement! It feels much better working in the terminal now - everything is super responsive.

I'm glad to hear that!

> Thank you.

You're welcome!


> Also, the ability to enable and adjust the smoothScrollDuration option of Terminal(xterm.js) would be helpful - but that is just a personal preference.

Alright, this is also a good suggestion. I have added an ability to pass custom options to Xterm config. E.g., running in the browser console the following will get what you need:

```JS
config_portable_module_xterm_options = JSON.stringify({'smoothScrollDuration': '200'});
theme.config.save();
```

**Comment by robertthemay** [comment]
> I have added an ability to pass custom options to Xterm config.
Icing on the cake. Thank you.
