### ISSUE TITLE
Disable horizontal scroll bar and do a wrap text instead ...

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1657]
It seems that the `Scheduled Cron Jobs` now have got a horizontal scroll bar that is very thin and when i want to move a cron job i have to scroll to the right to click on the arrow and when the cron job has moved it jumps back to the left again, so i have to scroll to the right again and click on the arrow and so on. Very annoying.

Could you add an option to make the cron job do a wrap text instead (as it was before), so it won't add that horizontal scroll bar?

AT: 20.30-RC1-74

**Comment by iliajie** [comment]
Hello,

Please provide a screenshot to make sure we're on the same page.

**Comment by Sopor** [comment]
Now:
![image](https://github.com/webmin/authentic-theme/assets/5789283/6820a7c8-2478-4b20-9149-dfaa3cc63284)

Before:
![image](https://github.com/webmin/authentic-theme/assets/5789283/7fab89ca-044e-4b05-9d10-2db92d448b24)

The page will be longer but that is much better to see everything than scrolling the cron jobs.

**Comment by iliajie** [comment]
> The page will be longer but that is much better to see everything than scrolling the cron jobs.

Why do you say "longer" while talking about horizontal scrollbar?

**Comment by Sopor** [comment]
Without the horizontal scrollbar the page will be longer because the text use two lines instead of one and i don't see that as an issue.

**Comment by iliajie** [comment]
This is common to have horizontal scrollbar displayed for the content that isn't meant to be wrapped. 

What is the real problem in having horizontal scrollbar?

**Comment by Sopor** [comment]
As i explained in my first post (moving cron jobs), but also i can't read the whole cron job without scrolling.

Have you ever seen a web page with horizontal scrollbar?

The scrollbar is also thin and difficult to click on (i often click on the cron job instead of the scrollbar) and when you scroll and you don't scroll perfect to left or right (you move the mouse pointer too much up or down) the mouse will lose the scrollbar and you have to start over again.

**Comment by iliajie** [comment]
> The scrollbar is also thin and difficult to click on (i often click on the cron job instead of the scrollbar)

Nobody should ever click on the scroll bar, or interact with the scrollbar directly! There is a _mousewheel_ for doing the scrolling job. For horizontal scroll however, you would need to use _Shift+Mousewheel_ to perform the horizontal scroll.

> As i explained in my first post (moving cron jobs), but also i can't read the whole cron job without scrolling.

By the way, there is an option to change the length of the command length, i.e. _Maximum command length to display_ in Cron module config.

> Have you ever seen a web page with horizontal scrollbar?

I did. I personally, don't like to wrap the long command text inside of the table cell, it just looks less readable. Although, I could make it optional for a user to choose ..

**Comment by Sopor** [comment]
> Although, I could make it optional for a user to choose ..

That would be really nice if you could do that 🤗

**Comment by iliajie** [comment]
Alright, it was implemented on the latest commit. Try installing latest update, open browser's console and run:

```
settings_right_table_wrap_inside_scrolled_container = true;
theme.config.save();
```

.. then after refreshing the page, it should do what you expect.

**Comment by Sopor** [comment]
Nice, it worked, but how should i remember all these console commands?

Do you have a list of console command somewhere, so everyone can use them?

There must be more than this one?

**Comment by iliajie** [comment]
There are plenty of options listed in `default.js` file which cannot be controlled via UI, because of its unpopularity.

**Comment by Sopor** [comment]
> There are plenty of options listed in `default.js` file which cannot be controlled via UI, because of its unpopularity.

Yeah, but all are not easy to understand for everyone 😥
