### ISSUE TITLE
Show complete version when updating developer version

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1658]
When i want to update i can't see what version you are on because it will always show RC1:
`(installed version 20.30-RC1, latest stable 20.22)`

So, I get to take a chance if there is a new version or not 😔

Can't you show the same version as you show on the dashboard `20.30-RC1-74`, so i know there is a new version to install?

**Comment by iliajie** [comment]
> (installed version 20.30-RC1, latest stable 20.22)

I will fix that. Yet, you can see the minor version on the dashboard.

**Comment by iliajie** [comment]
> Can't you show the same version as you show on the dashboard `20.30-RC1-74`, so i know there is a new version to install?

May be. This is very low priority.

**Comment by iliajie** [comment]
Alright, I have taken a closer look and I agree, it's a bit confusing. Fixed on the latest commit.

**Comment by Sopor** [comment]
Is this really correct `(installed version 20.30-RC1-78, latest stable 20.22, latest development 20.30-RC1-75)`?

How can i run 78 when the latest version is 75?

**Comment by iliajie** [comment]
> How can i run 78 when the latest version is 75?

You're seeing this, because remote version number is being cached.

**Comment by Sopor** [comment]
Yes, now it is showing the correct version 👍
