### ISSUE TITLE
No tooltip on this button ...

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1660]
When hover the mouse over the module config i get a tooltip:
![image](https://github.com/webmin/authentic-theme/assets/5789283/f5562510-bf0f-4d99-bd78-13c2307de277)

But this button has no tooltip and i don't even know what the name is for the button:
![image](https://github.com/webmin/authentic-theme/assets/5789283/90fe3a41-f4bd-45e3-8c42-96d9d0a49c16)

It seems to change the configuration pages from columns to lines, but a tooltip would have been nice to tell the user what it does.

**Comment by iliajie** [comment]
> It seems to change the configuration pages from columns to lines, but a tooltip would have been nice to tell the user what it does.

Yeah yeah, your right! Although, this is a temp button. It will be replaced with almighty popover to enable user to choose number of maximum columns in the row or change back to the old layout and/or completely remove it from the table header ..

**Comment by iliajie** [comment]
Implemented!

This is the example of how layout control widget can be used to change page layout:

https://github.com/webmin/authentic-theme/assets/4426533/be32c891-0823-4b62-af38-6f248d1e2fe6
