### ISSUE TITLE
Cron job: How do disable the `Move` column?

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1661]
I have looked around in the module config for cron job and i can't find any settings for the `Move` column:
![image](https://github.com/webmin/authentic-theme/assets/5789283/6df7377b-4c0f-4de7-a774-e766723b3046)

**Comment by iliajie** [comment]
What settings are you looking to find though?

**Comment by Sopor** [comment]
Sorry, forget it.

I don't know what i was thinking.

Move is that column with arrows to move cron job entries up and down.

I must have got a totally blackout 😵
