### ISSUE TITLE
unable to install v21

### ISSUE THREAD

**Issue by jtabox** [webmin/authentic-theme#1662]
Hey, not sure if this is intended or not, but couldn't find any relevant info so I thought I'd ask.

Trying to install the latest version of Authentic Theme (21.00) brings up an error message that "Installing this version requires latest and/or possibly unreleased version of Webmin [...] Continuing upgrade operation using UI is not possible." - see the screenshot below.

https://i.imgur.com/Rg8gCDG.png

I'm using the latest version of Webmin (2.021). Tried to install the new version of Authentic Theme the normal way, went to Theme Updates module, it said I had v20.22 installed and that a new stable release v21.00 was out, so I pressed the Update Theme button.

Is this error because there's a new version of Webmin? Or can I install v21.00 of Authentic Theme but not via UI? Is there some script to run on console? Not really sure if I'm supposed to install the new version or not.

**Comment by iliajie** [comment]
Hello,

> Is this error because there's a new version of Webmin?

Yes, yet unreleased.

> Or can I install v21.00 of Authentic Theme but not via UI?

No, as it may break some modules, in particular **Read User Mail** and **Terminal**.

> Not really sure if I'm supposed to install the new version or not.

It should only be installed with latest Webmin code.

You should wait for the new Webmin 2.100.

**Comment by iliajie** [comment]
Yeah, actually, I think we should show the new version in that part of the UI, even if it's not installable.

Thanks for the heads up!
