### ISSUE TITLE
Dashboard: System uptime is empty

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1664]
This is not a big deal, it only looks empty when the System uptime is not showing anything:

![image](https://github.com/webmin/authentic-theme/assets/5789283/d1420d32-b4fd-4cff-9d63-d13b09102175)

It is only empty a minute after a reboot, but it can make new users a bit confused when the system time is showing nothing.

I assume system uptime shows 0 before it reaches 1 minute (or is it empty if i run the command from a terminal too?), so why isn't that visible on the dashboard?

**Comment by iliajie** [comment]
> so why isn't that visible on the dashboard?

Because of aggressive caching. I'll have a look.

**Comment by iliajie** [comment]
This issue will be fixed in the next Webmin release.

Thanks for the heads up!
