### ISSUE TITLE
Change Language and Theme: No `Changes you have made may not be saved`

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1665]
When changing settings in `Change Language and Theme` i don't get the below question when i leave without saving:

![image](https://github.com/webmin/authentic-theme/assets/5789283/32f18457-43c9-43b1-b354-7787e99dcd27)

**Comment by jcameron** [comment]
@iliajie this is coming from the theme I believe?

**Comment by iliajie** [comment]
Yeah .. It's very minor issue .. I will take a look at it anyway but some time later ..

**Comment by Sopor** [comment]
I like minor issues, because no one else will find them and report them 😋

**Comment by iliajie** [comment]
> I like minor issues, because no one else will find them and report them 😋

Thank you for reporting this! It will be fixed in the next Authentic Theme 21.07 release.
