### ISSUE TITLE
I followed the instructions on `https://webmin.com/download` and i have Dates format instead of Locale

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1666]
I installed a new Webmin and i did as you @iliajie told me to do, but the date and time use `Dates format` and not `Locale`.

I followed the instructions on `https://webmin.com/download`.

![image](https://github.com/webmin/authentic-theme/assets/5789283/9e74c643-d07b-46a1-b62d-f1b2883a0ca1)

This is a total new installation of DietPi running Debian 12.

Shouldn't everything be installed by running `apt install webmin`?

**Comment by iliajie** [comment]
Hello,

Yes. Everything should be installed but only if packages are provided by your OS. For instance, my version of Debian 12 have all the dependencies installed.

**Comment by Sopor** [comment]
I ran the command you told me to do [here](https://github.com/webmin/authentic-theme/issues/1663#issuecomment-1660227408) and why would it try to install all this if the Webmin installation includes everything?

How on earth should someone know that all these extra libraries are needed?

If i follow the install instructions i assume everything will be installed.

```
~$ sudo apt install libdatetime-perl libdatetime-timezone-perl libdatetime-locale-perl libtime-piece-perl
[sudo] password for granberg:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'perl' instead of 'libtime-piece-perl'
perl is already the newest version (5.36.0-7).
perl set to manually installed.
The following additional packages will be installed:
  libalgorithm-c3-perl libb-hooks-endofscope-perl libb-hooks-op-check-perl libclass-c3-perl libclass-data-inheritable-perl libclass-inspector-perl
  libclass-method-modifiers-perl libclass-singleton-perl libdata-optlist-perl libdevel-callchecker-perl libdevel-stacktrace-perl
  libdynaloader-functions-perl libeval-closure-perl libexception-class-perl libfile-sharedir-perl libmodule-implementation-perl
  libmodule-runtime-perl libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl libpackage-stash-perl libparams-classify-perl
  libparams-util-perl libparams-validationcompiler-perl librole-tiny-perl libspecio-perl libsub-exporter-perl libsub-exporter-progressive-perl
  libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl libtry-tiny-perl libvariable-magic-perl libxstring-perl
Suggested packages:
  libscalar-number-perl libtest-fatal-perl
Recommended packages:
  libclass-c3-xs-perl libdevel-lexalias-perl libpackage-stash-xs-perl libclass-xsaccessor-perl libref-util-perl
The following NEW packages will be installed:
  libalgorithm-c3-perl libb-hooks-endofscope-perl libb-hooks-op-check-perl libclass-c3-perl libclass-data-inheritable-perl libclass-inspector-perl
  libclass-method-modifiers-perl libclass-singleton-perl libdata-optlist-perl libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl
  libdevel-callchecker-perl libdevel-stacktrace-perl libdynaloader-functions-perl libeval-closure-perl libexception-class-perl libfile-sharedir-perl
  libmodule-implementation-perl libmodule-runtime-perl libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl libpackage-stash-perl
  libparams-classify-perl libparams-util-perl libparams-validationcompiler-perl librole-tiny-perl libspecio-perl libsub-exporter-perl
  libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl libtry-tiny-perl
  libvariable-magic-perl libxstring-perl
0 upgraded, 38 newly installed, 0 to remove and 0 not upgraded.
Need to get 3927 kB of archives.
After this operation, 30.0 MB of additional disk space will be used.
```

**Comment by iliajie** [comment]
> How on earth should someone know that all these extra packages are needed?

You don't need to know anything, just use the instructions from [webmin.com](https://webmin.com/download/#repository), i.e.:

```
curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
apt-get install webmin
```

> If i follow the install instructions i assume everything will be installed.

Which instructions did you follow exactly?

**Comment by Sopor** [comment]
I did exactly as described on the webmin page

```
curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
apt install webmin
```

BTW, `apt-get` is changed to `apt`, but both do work.

**Comment by iliajie** [comment]
Which Debian instance are you using exactly? Do you have download link?

**Comment by Sopor** [comment]
DietPi and this was on an older RPi 2, so i have to use the ARMv7 version:
`https://dietpi.com/downloads/images/DietPi_RPi-ARMv7-Bookworm.7z`

**Comment by Sopor** [comment]
> Suggested packages:
>   libscalar-number-perl libtest-fatal-perl
> Recommended packages:
>   libclass-c3-xs-perl libdevel-lexalias-perl libpackage-stash-xs-perl libclass-xsaccessor-perl libref-util-perl

I also wondering if all these packages will be installed?

It is only recommended and suggested packages, so if i get this right they will not be installed if i won't do it manually.

Do i really need them to get Webmin to work?

**Comment by iliajie** [comment]
I have tried DietPi Bookwork NativePC (Minimal), e.g.:

<img width="718" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/c3f87c8e-5891-4506-bce9-0a5b4b389208">

Interesting distro, never used it before.



> I did exactly as described on the webmin page. That is why i think something isn't right.

Apparently, APT defaults can be different, the solution for your problem is as simple as:

```
apt-get install webmin --install-recommends
```

**Comment by Sopor** [comment]
So, it is the recommender packages that are missing and to get them to install i need to add `--install-recommends`?
`libclass-c3-xs-perl libdevel-lexalias-perl libpackage-stash-xs-perl libclass-xsaccessor-perl libref-util-perl`

You follow guides because you want a smooth installation, but that is not what you get. 😥

Any reason that you can't update your guide to: `apt install webmin --install-recommends` in case someone else get the same problem as i did? Will it harm something if `--install-recommends` isn't needed and you use that option?

**Comment by iliajie** [comment]
> So, it is the recommender packages that are missing and to get them to install i need to add `--install-recommends`?
> You follow guides because you want a smooth installation, but that is not what you get. 😥

Yes. I have updated the docs as well.

> Any reason that you can't update your guide to: apt install webmin --install-recommends in case someone else get the same problem as i did? Will it harm something if --install-recommends isn't needed and you use that option?

I already did. @jcameron Jamie, please rebuild _webmin.com_.

**Comment by jcameron** [comment]
Ok, doing it now ..

**Comment by iliajie** [comment]
Perfect, thanks!
