### ISSUE TITLE
Implement a way to change default for password visibility when changing password

### ISSUE THREAD

**Issue by lukembis** [webmin/authentic-theme#1669]
Following on from #1327 

It would be good to be able to change the default behaviour for password visibility when changing a password in the 'Change Password' module. Currently the default is to show password.

**Comment by jcameron** [comment]
@iliajie can you take a look at this since you fixed the linked issue..

**Comment by iliajie** [comment]
Yeah, I think I will just make the theme remember the last state for password filed visibility, and apply on each page load whatever was used last for each user.

**Comment by iliajie** [comment]
Next Authentic Theme release will have support for storing password visibility based on the page and the user.

You can install latest devel version of theme from theme configuration page to give it a try now.
