### ISSUE TITLE
Undefined subroutine &virtual_server::get_module_version_and_type called

### ISSUE THREAD

**Issue by tech3652023** [webmin/authentic-theme#1670]
HI Have problem with authentic-theme after upgrade on 3 of our vps running webmin virtualmin, authentic-theme

when we  go dashboard '/sysinfo.cgi?xnavigation=1' we get this error below we have re-installed webmin and hard reset on webmin uploaded to latest authentic-theme but still having errors server mix are Deb 10, Deb11.

HTTP/1.0 500 Perl execution failed Server: MiniServ/2.101 Date: Tue, 22 Aug 2023 10:18:22 GMT Content-type: text/html; Charset=utf-8 Connection: close
Error — Perl execution failed

Undefined subroutine &virtual_server::get_module_version_and_type called at /usr/share/webmin/authentic-theme/authentic-lib.pl line 699.

Many thanks
Darren

**Comment by iliajie** [comment]
Hey, Darren!

Try manually restating Webmin by running `/etc/webmin/restart`. If that doesn't help try running `/etc/webmin/restart-by-force-kill` command.

**Comment by tech3652023** [comment]
HI Thank you for your quick reply I have tried both options above just retried theme again and cleared all browser cache just in case but with same issue ?

**Comment by iliajie** [comment]
> Undefined subroutine &virtual_server::get_module_version_and_type called at /usr/share/webmin/authentic-theme/authentic-lib.pl line 699.

What is your Virtualmin version installed?

**Comment by tech3652023** [comment]
Hi webmin-virtual-server  6.09.gpl

**Comment by iliajie** [comment]
That seems like a problem! Delete all existing `virtualmin.com` repos from `/etc/apt`, run the following command to setup Virtualmin repos:

```
wget https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh
sh virtualmin-install.sh --setup
```

.. and then run `apt-get update && apt-get upgrade` to install latest Virtualmin version.

**Comment by tech3652023** [comment]
HI perfect thank you solved
