### ISSUE TITLE
Dialog Layout button appears to always change navigation menu Color pallette to the Default colour

### ISSUE THREAD

**Issue by ksihota** [webmin/authentic-theme#1671]
I am noticing an unexpected behaviour when using the button that can change some dialog views from vertical to horizontal that I believe was added recently. At least I only noticed it recently.
![image](https://github.com/webmin/authentic-theme/assets/29150649/1e401820-7346-475b-80ca-deb8854906b6)
Not sure where to submit this but I have a strange colour background behaviour.
I have my backgounds set to White but when I make a change to the layout that was added (top left corner) to some dialogs the background for the left navigation panel changes from White to Blue. 

I have tried to see when it happens and have been able to reproduce it by Selecting Virtual server 
![image](https://github.com/webmin/authentic-theme/assets/29150649/d57b497a-ad61-4602-8c8e-13fca6f5ca3b)

Select the botton and select save. Then return to Virtual server. The menu switches to the Dark Blue background.
To switch it back to white I go into Theme configuration and switch the navigation menu colour back to White. It appears to automatically revert to the Default which is set to Blue.
![image](https://github.com/webmin/authentic-theme/assets/29150649/324095be-4fd6-4330-889e-d5bd66ad7e69)

Its a little bit irritating.

**Comment by iliajie** [comment]
Hello,

You're right! Sadly there was a bug that caused other theme options not saved. Fixed in the latest commit. You can install patched version using Theme Configuration page!

Thanks for the heads up!
