### ISSUE TITLE
Add 'required' attribute to login

### ISSUE THREAD

**Issue by PitWenkin** [webmin/authentic-theme#1672]
I think this is the right place to make Webmin/Virtuamin loginfields required, to prevent submitting a login without username and/or password filled out?

https://github.com/webmin/authentic-theme/blob/9535b5915142f2b26f8a1c3212de47b4e904b524/session_login.cgi#L170
https://github.com/webmin/authentic-theme/blob/9535b5915142f2b26f8a1c3212de47b4e904b524/session_login.cgi#L183

I hope that there is no use-case where passwords are empty …

**Comment by iliajie** [comment]
Hello,

No, it is not. Because technically it's possible to set Webmin password to blank and login with no password. It is a very bad idea but it is possible.
