### ISSUE TITLE
Terminal screen shrunk/not properly zoomed in LibreWolf browser (Firefox fork)

### ISSUE THREAD

**Issue by c-prompt** [webmin/authentic-theme#1674]
I'm assuming this is theme/css related but please move if otherwise.

Upon using the Virtualmin terminal (without any input), the command line screen looks like this in the LibreWolf browser (Chrome appears fine so it is browser-specific but I don't have Firefox to test if the problem's unique to LibreWolf or Firefox more broadly):

![Virtualmin Terminal LibreWolf1](https://github.com/webmin/authentic-theme/assets/10625352/71a7ac7f-0301-4767-a0cd-f3db2b56e6f2)

When I enter a command (e.g., csf -ra), the screen looks as such:

![Virtualmin Terminal LibreWolf2](https://github.com/webmin/authentic-theme/assets/10625352/6166a489-fc9d-4cbb-ae1b-a56d944f1204)

I'm seeing the following error in the browser's Inspector: "_This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”._" I don't know that this is causing the problem as the error also shows on the non-terminal Virtualmin pages and those all look proper.

I don't remember which version of Virtualmin (or LibreWolf) this started but I know I had the issue long before I upgraded from Debian 10.

Operating system 	Debian Linux 11
Webmin version 	2.101
Usermin version 	2.001
Virtualmin version 	7.7  
Authentic theme version 	21.05
LibreWolf 117.0-1

**Comment by iliajie** [comment]
Try opening the browser's console and run:

```
config_portable_module_xterm_render_addon = false;
theme.config.save();
```

It works perfectly fine in Firefox.

**Comment by c-prompt** [comment]
> Try opening the browser's console and run:
> 
> ```
> config_portable_module_xterm_render_addon = false;
> theme.config.save();
> ```
> 
> It works perfectly fine in Firefox.

Yes, that does solve the problem. Thank you.

**Comment by iliajie** [comment]
Next Authentic Theme release will have support for disabling WebGL addon for Terminal module in module config!

**Comment by c-prompt** [comment]
> Next Authentic Theme release will have support for disabling WebGL addon for Terminal module in module config!

Currently using Authentic Theme version 21.09.5 and see this problem again. This time, executing the [above console commands](https://github.com/webmin/authentic-theme/issues/1674#issuecomment-1708093747) doesn't help. However, if I just bring up the terminal (e.g., by typing terminal in the search bar rather than clicking on the terminal icon in the lower-left sidebar), it looks OK. I have disabled Enable WebGL rendering addon (i.e., set to no).

Terminal via icon:
![Terminal via icon](https://github.com/webmin/authentic-theme/assets/10625352/8c79cd21-5c81-4d15-8d7b-e1399e39cd8d)

Terminal via search:
![Terminal via Search](https://github.com/webmin/authentic-theme/assets/10625352/57e92a2b-6b6e-40fe-900f-f2e500889391)

LibreWolf 124.0.1-1
Operating system 	Debian Linux 12
Webmin version 	2.105
Usermin version 	2.005
Virtualmin version 	7.10.0  
Authentic theme version 	21.09.5

**Comment by iliajie** [comment]
Hello,

Could you try the lates nightly version of Webmin and see if it fixes your issue?

**Comment by c-prompt** [comment]
> Hello,
> 
> Could you try the lates nightly version of Webmin and see if it fixes your issue?

Be happy to. I see https://builds.webmin.dev/webmin-latest.deb on https://builds.webmin.dev/ but it's not clear how to update. Is there an update script? Or what's the URL for a changed apt source? Thanks.

**Comment by iliajie** [comment]
Download it and use `apt-get install ./webmin-latest.deb` command.

**Comment by c-prompt** [comment]
Well done - that fixed it. Thanks for the quick response. However, what concern should I have about the permission denied error at the bottom?

Get:1 http://deb.debian.org/debian bookworm/main amd64 libqrencode4 amd64 4.1.1-1 [40.4 kB]
Get:2 /root/webmin-latest.deb webmin all 2.105.202404071621 [10.3 MB]
Get:3 http://deb.debian.org/debian bookworm/main amd64 qrencode amd64 4.1.1-1 [42.6 kB]
Fetched 83.0 kB in 0s (653 kB/s)
[master da36f3e] saving uncommitted changes in /etc prior to apt run
 15 files changed, 175 insertions(+), 13 deletions(-)
 create mode 100644 ssh/sshd_config.save
 create mode 100644 usermin/authentic-theme/scripts.js
 create mode 100644 webmin/authentic-theme/scripts.js
 create mode 100644 webmin/sshd/version
 create mode 100755 webmin/xterm/shellserver.pl
Reading changelogs... Done
(Reading database ... 150561 files and directories currently installed.)
Preparing to unpack /root/webmin-latest.deb ...
Unpacking webmin (2.105.202404071621) over (2.105) ...
Selecting previously unselected package libqrencode4:amd64.
Preparing to unpack .../libqrencode4_4.1.1-1_amd64.deb ...
Unpacking libqrencode4:amd64 (4.1.1-1) ...
Selecting previously unselected package qrencode.
Preparing to unpack .../qrencode_4.1.1-1_amd64.deb ...
Unpacking qrencode (4.1.1-1) ...
Setting up webmin (2.105.202404071621) ...
Setting up libqrencode4:amd64 (4.1.1-1) ...
Setting up qrencode (4.1.1-1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for libc-bin (2.36-9+deb12u4) ...
[master ec00f01] committing changes in /etc made by "apt-get install ./webmin-latest.deb"
 9 files changed, 24 insertions(+), 16 deletions(-)
 delete mode 100644 webmin/postfix/version
**N: Download is performed unsandboxed as root as file '/root/webmin-latest.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)**

**Comment by iliajie** [comment]
It's good to know that it worked for you!

The notice can be ignored.

**Comment by c-prompt** [comment]
> It's good to know that it worked for you!
> 
> The notice can be ignored.

Here's hoping the production release (when it's released) overwrites the nightly build so I can get back on the production track ;)

**Comment by iliajie** [comment]
Yes, of course it will. No worries.
