### ISSUE TITLE
Extra entries

### ISSUE THREAD

**Issue by stachyc** [webmin/authentic-theme#1677]
Hello,

I am using 
{'extra':[{'title': 'Service Manager', 'link': 'https://192.168.13.60:34023/', 'icon': 'asterisk', 'level': '0,1,2,3,4'}, {'title': 'HMI', 'link': 'http://192.168.13.60/', 'icon': 'server',  'level': '0,1,2,3,4'}]} in extra entries. Is same way to open in right part webmin ? This configuration open new tab in browser ?

**Comment by iliajie** [comment]
Hello,

You cannot open anything in the right content window, unless it's a Webmin module/page.

That said, if `192.168.13.60:34023` is a standalone app, then it's expected to have it opened in the new tab.

**Comment by iliajie** [comment]
No, there is no real "right side". It isn't a frame. You cannot open anything in it. Only Webmin modules. However, technically (and theoretically) speaking you could probably open other programs using Webmin UI lib in the "right side", but I don't think you should try to do it.

**Comment by stachyc** [comment]
ok, thx.
