### ISSUE TITLE
Show table icon links in grayscale unless hovered - is not respected when in Night mode

### ISSUE THREAD

**Issue by shoulders** [webmin/authentic-theme#1682]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.101      |
|  Usermin version     |     2.001     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.04      |
|  Package updates     |      2  package updates are available   |

I am aware that some options in dark mode might be ignored and that might be the case here, but I think that if this is not a bug then this option should be enabled to work in dark mode as a feature, it will give my eyes stuff to focus on and can be toggled on/off by other users so no-one will have to change their workflow.

When I have Night mode selected and  **Show table icon links in grayscale unless hovered** set to **No**, the icons will not display in colour. They work fine in day mode.

### Theme Setting
![image](https://github.com/webmin/authentic-theme/assets/319997/655f8022-c7d6-4a62-8175-3a0caca40853)

### Night mode
![image](https://github.com/webmin/authentic-theme/assets/319997/2571e44a-2a56-48b8-a1c1-66fc0db69c23)

### Day mode
![image](https://github.com/webmin/authentic-theme/assets/319997/f71ce922-497d-4dea-9f9d-eaee7634c264)

**Comment by iliajie** [comment]
Hello, 

Thanks for the heads up! It will be fixed in the next Webmin release!
