### ISSUE TITLE
Starting a KVM host fails Debian 12.x

### ISSUE THREAD

**Issue by forlotto** [webmin/authentic-theme#1684]
When trying to start a KVM host it needs to look for Qemu and KVM packages fail using the Cloudmin script.

Setting up KVM host system ..
Checking system status ..
.. done
Installing required commands ..
.. done
Turning off AppArmor ..
.. done
Installing KVM packages ..
.. installation failed : Reading package lists... Building dependency tree... Reading state information... Package kvm is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source Package qemu is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source W: --force-yes is deprecated, use one of the options starting with --allow instead. E: Package 'kvm' has no installation candidate E: Package 'qemu' has no installation candidate
.. setup failed! See the error message above.

Would rather not attempt to break upgrade path by going with backports etc... 

Any suggestions? Using the pro version.

**Comment by iliajie** [comment]
> E: Package 'kvm' has no installation candidate

KVM is not installed via a package named `kvm`. 

   Try installing it with:

   ```sh
   apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
   ```

@jcameron Jamie, the Cloudmin installer should use the correct package name.

Also, we need to create a new repo under `GitHub.com/webmin` for Cloudmin users, like `cloudmin-gpl` or `server-manager`, so users would be able to report the problem in the right place.

**Comment by forlotto** [comment]
uilding dependency tree... Done
Reading state information... Done
Note, selecting 'qemu-system-x86' instead of 'qemu-kvm'
                                                       The following additional packages will be installed:
                                                                                                             gnutls-bin ibverbs-providers iptables ipxe-qemu libcacard0 libcapstone4 libdaxctl1 libexecs0 libfdt1 libfmt9 libgfapi0 libgfrpc0 libgfxdr0 libglusterfs0 libgnutls-dane0 libibverbs1 libip6tc2 libiscsi7 libndctl6 libnss-mymachines
                                                                                                    libpmem1 librados2 librbd1 librdmacm1 libslirp0 libspice-server1 libssh-4 libtpms0 libunbound8 liburing2 libusbredirparser1 libvdeplug2 libvirglrenderer1 libvirt-daemon libvirt-daemon-config-network libvirt-daemon-config-nwfilter
                                                                                            libvirt-daemon-driver-lxc libvirt-daemon-driver-qemu libvirt-daemon-driver-vbox libvirt-daemon-driver-xen libvirt-daemon-system-systemd libvirt-l10n libvirt0 libxencall1 libxendevicemodel1 libxenevtchn1 libxenforeignmemory1
                                                                              libxengnttab1 libxenhypfs1 libxenmisc4.17 libxenstore4 libxentoolcore1 libxentoollog1 libxml2-utils mdevctl netcat-openbsd ovmf qemu-block-extra qemu-system-common qemu-system-data qemu-system-gui qemu-utils seabios swtpm swtpm-libs
                                                                         swtpm-tools systemd-container
                                                                                                      Suggested packages:
                                                                                                                           firewalld libvirt-clients-qemu libvirt-login-shell libvirt-daemon-driver-storage-gluster libvirt-daemon-driver-storage-iscsi-direct libvirt-daemon-driver-storage-rbd libvirt-daemon-driver-storage-zfs numad auditd nfs-common open-iscsi
                                                                                                                        pm-utils systemtap zfsutils samba vde2 trousers
                                                                                                                                                                       The following NEW packages will be installed:
                                                                                                                                                                                                                      bridge-utils gnutls-bin ibverbs-providers iptables ipxe-qemu libcacard0 libcapstone4 libdaxctl1 libexecs0 libfdt1 libfmt9 libgfapi0 libgfrpc0 libgfxdr0 libglusterfs0 libgnutls-dane0 libibverbs1 libip6tc2 libiscsi7 libndctl6
                                                                                                                                                                                                        libnss-mymachines libpmem1 librados2 librbd1 librdmacm1 libslirp0 libspice-server1 libssh-4 libtpms0 libunbound8 liburing2 libusbredirparser1 libvdeplug2 libvirglrenderer1 libvirt-clients libvirt-daemon libvirt-daemon-config-network
                                                                                                                                                                                                   libvirt-daemon-config-nwfilter libvirt-daemon-driver-lxc libvirt-daemon-driver-qemu libvirt-daemon-driver-vbox libvirt-daemon-driver-xen libvirt-daemon-system libvirt-daemon-system-systemd libvirt-l10n libvirt0 libxencall1
                                                                                                                                                                                    libxendevicemodel1 libxenevtchn1 libxenforeignmemory1 libxengnttab1 libxenhypfs1 libxenmisc4.17 libxenstore4 libxentoolcore1 libxentoollog1 libxml2-utils mdevctl netcat-openbsd ovmf qemu-block-extra qemu-system-common qemu-system-data
                                                                                                                                                                                 qemu-system-gui qemu-system-x86 qemu-utils seabios swtpm swtpm-libs swtpm-tools systemd-container
                                   0 upgraded, 71 newly installed, 0 to remove and 0 not upgraded.
                                                                                                  Need to get 55.4 MB of archives.
                                                                                                                                  After this operation, 188 MB of additional disk space will be used.

It appears it selects qemu-x86 instead ? Errr yeah better ask first before shooting I presume. 

Also the terminal in webmin is one hell of a klunky interface it works part time and outputs text to the screen like modern art it doesn't keep any particular format or look anything like a cli would ... And it hangs up and don't show inputed text.

**Comment by forlotto** [comment]
Well it worked I figured it isn't that hard to start from scratch done it 12 times in the past 3 days with different configurations thinking maybe something with webmin and users wasn't jiving as user didn't match server etc I know users are created with virtualmin so I figured maybe my user had to be specific as well.... Anyways thanks I can move on to further testing for now.

**Comment by forlotto** [comment]
Don't know should I open up another issue for the Terminal? I know you guys are pretty big on reporting issues individually so I think I will...

**Comment by iliajie** [comment]
> Well it worked I figured

Glad to hear that!

> Don't know should I open up another issue for the Terminal? 

Yes, always start a new thread for a new question!

**Comment by forlotto** [comment]
Thanks much appreciated! You folks are awesome at virtualmin/cloudmin/webmin. Can't wait to dig in a little further as I get time. Hopefully Jamie addresses the issue however I am Pro cloudmin Pro virtualmin so the GPL stuff you mentioned for Jamie to fix may or may not fix my issue depending on how repos are setup to grab what from what maybe GPL and PRO are the same files ?

If I ever come into a decent amount of cash I'd love to partner with this company and get folks on board to bring it up to speed financially and keep things cheap and free at the same time ;) Could happen I'll tell you either way you guys are doing Gods work essentially whether you are athiest or not what you are doing has more value than currency using "Gods Work" as the only extrapolation I can really put into terms. You're making software that doesn't judge, doesn't force, doesn't pillage. 

Problem still exists but at least you know and from what I can tell Jamie has to fix it on your end but at least it is documented and known of.

**Comment by jcameron** [comment]
Yeah it looks like we need to update the installer to handle different package names on Debian 12.

@forlotto which URL did you download the installer from?

**Comment by forlotto** [comment]
Private URL with key Pro Version From Website.

**Comment by forlotto** [comment]
wget -O cloudmin-install.sh https://cloudmin.virtualmin.com/cgi-bin/cloudmin-debian-install.cgi?serial=111111\&key=abcdefg; /usr/bin/sudo /bin/sh cloudmin-install.sh

**Comment by jcameron** [comment]
Ok I see, the failure isn't in the install script, it's in the KVM host setup in Cloudmin itself. We'll fix this in the next release...
