### ISSUE TITLE
Export of the authentic-theme with customizations.

### ISSUE THREAD

**Issue by CharlyAes32** [webmin/authentic-theme#1686]
Hello, I personalized the Authentic-theme by adding images for logged in, non-logged in users and a wallpaper for the login.
I would like to be able to export these customizations to put them on another webmin. How to proceed ?
This is the first point.
The second point is that I would like to apply a border-radius to the login form.
I can do this with the browser inspector, but where should I make this change in the theme?
Thank you for your help.
Arnaud

**Comment by CharlyAes32** [comment]
> Hello,
> 
> > I would like to be able to export these customizations to put them on another webmin. How to proceed ?
> 
> Theme configs are stored in `/etc/webmin/authentic-theme` directory.
> 
> > I can do this with the browser inspector, but where should I make this change in the theme?
> 
> You could use **Theme Configuration -> Theme Extensions** for this purpose.

Thank you for the quick reply.
I applied the border-radius as intended.
So, if I understood correctly, by exporting the /etc/webmin/authentic-theme folder, and I put it instead on the other server, the changes will be applied?
Sorry, it's just so we don't do anything stupid or bother you any longer.

**Comment by iliajie** [comment]
> So, if I understood correctly, by exporting the /etc/webmin/authentic-theme folder, and I put it instead on the other server, the changes will be applied?

Yep!

> Sorry, it's just so we don't do anything stupid or bother you any longer.

No problemo!

**Comment by CharlyAes32** [comment]
It seems that by just exporting /etc/webmin/authentic-theme no changes are applied to the connection on the other server

> > So, if I understood correctly, by exporting the /etc/webmin/authentic-theme folder, and I put it instead on the other server, the changes will be applied?
> 
> Yep!
> 
> > Sorry, it's just so we don't do anything stupid or bother you any longer.
> 
> No problemo!

It seems that by just exporting /etc/webmin/authentic-theme no changes are applied to the connection on the other server.
Always the same old interface with no customizations.

**Comment by iliajie** [comment]
> Always the same old interface with no customizations.

If you mean the theme, then it has to be set in `/etc/webmin/config` and `/etc/webmin/miniserv.conf` files.

**Comment by CharlyAes32** [comment]
Sorry, it's my fault, I exported to a folder /etc/webmin/authentic-theme instead of /etc/webmin/
Problem solved.
THANKS
