### ISSUE TITLE
Webmin cannot be installed as an APP from the login screen

### ISSUE THREAD

**Issue by shoulders** [webmin/authentic-theme#1687]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      19  package updates are available   |

## Background
Through chrome on an android phone you can install websites as apps on your phone (very handy) if it has a proper manifest file and an appropriate declaration in the html.

## The Issue
In authentic-theme/webmin you cannot add webmin as an app from the login screen which is the first place you would land before adding webmin as an app, but you can add webmin as an app once you have logged in.

## Proposed Solution

Allow users to add Webmin as an APP at the login screen by doing the following

- Add the html code into the login screen
```html
<link data-link-ref crossorigin="use-credentials" rel="manifest" href="/manifest-webmin.json">
```
- Make the `/manifest-webmin.json` available before login.

## Why
If I could not add a website as an APP before I logged in, I would not expect it to allow you to add it as an APP after you login.

This is a very useful feature and is becoming more popular.

## Related Issue
- https://github.com/webmin/authentic-theme/issues/1459

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! Although, this is already possible, e.g.:

<img width="1309" alt="image" src="https://github.com/webmin/authentic-theme/assets/4426533/ca510a73-37b0-45aa-89e0-e770c194b799">

However, you won't see this button unless you have legit (not self-signed) SSL certificate installed for your domain.

**Comment by shoulders** [comment]
:smile: the issue is that it cannot be done from the login screen, the code is missing

![image](https://github.com/webmin/authentic-theme/assets/319997/8bec5f7a-e2a8-452f-9bbd-cb367e15d316)

**Comment by iliajie** [comment]
Alright, thanks! Fixed on the latest commit!
