### ISSUE TITLE
get_pjax_content

### ISSUE THREAD

**Issue by DavidGhedini** [webmin/authentic-theme#1689]
Hi -
In the current theme, the get_pjax_content function has been removed.
We produced several popular Third Party Modules (Tomcat, Nagio, Certbot, etc..) that use this function.
Will it be reinstated or replaced or do we need to create our own solution?
Thanks

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up! The latest commit reinstates accidentally removed `get_pjax_content` and throws deprecation warning instead.
