### ISSUE TITLE
The sign out (log out) button is not easily reachable

### ISSUE THREAD

**Issue by SamSirry** [webmin/authentic-theme#1690]
This is an interface usability issue.
The only way I know of to sign out or log out the web interface is to click the little red arrow icon at the bottom of the left-side navigation menu, which happens to be pretty "down there" on the screen (on my 1080 pixel screen I need to scroll down), in Virtualmin or when a navigation section is open.

![image](https://github.com/virtualmin/virtualmin-gpl/assets/30126053/798d81ac-0587-4b8d-990d-d28078cae979)

I would suggest having the logout button/icon in a more prominent location and size. Perhaps, as with most online services, the top right corner of the screen would make a good candidate.

**Comment by iliajie** [comment]
Hello,

What if there was a hotkey for logging out, similarly it's implemented in MacOS, by hitting `Command (⌘)` + `Shift` + `Q`?

**Comment by SamSirry** [comment]
It would also be very productive to have a keyboard shortcut, but I never could figure out why they don't work on my Firefox (e.g. `Alt+F` or `Alt+K`).

I know a webpage can override the browser's default shortcut, but (aside from the fact that they aren't working on my browser) I can't be sure about `Ctrl+Shift+Q`, which is the shortcut for `File`->`Exit` on Firefox.

**Comment by iliajie** [comment]
> It would also be very productive to have a keyboard shortcut, but I never could figure out why they don't work on my Firefox (e.g. `Alt+F` or `Alt+K`).

Have you tried using **Theme Configuration** page to change default modifier key from `Alt` to something else?

**Comment by SamSirry** [comment]
> change default modifier key from `Alt` to something else

Cool! It works very well with `Ctrl`. Thank you for the tip ^_^

Can we have `Modifier`+`O` for Signing `O`ut?

**Comment by iliajie** [comment]
It could be more complex like `Ctrl+Alt+[` ..

**Comment by SamSirry** [comment]
> > Can we have `Modifier`+`O` for Signing `O`ut?
> 
> That would be '`O`pen file' in most Browsers (on Mac at least)

@PitWenkin,
I tend to think that all modern browsers have some option to allow the web page to override special keys. Otherwise, things like a Guacamole web console or VNC wouldn't work. Right?

![image](https://github.com/webmin/authentic-theme/assets/30126053/627ec036-06bd-4adb-b33b-d14c96562078)

**Comment by PitWenkin** [comment]
No matter if it would work or not, personally I think it should me a three letter combinaisonas @iliajie suggested.
Not to accidentally logging out users  …

**Comment by iliajie** [comment]
I'd prefer to have it set to `Alt + [`, where `Alt` is a default modifier and can be changed/configured. I don't think hitting `Alt + [` is that easy. But I think I will make it a combined hotkey, like `Alt + [`  + `Alt + [` ..

**Comment by iliajie** [comment]
Alright, the hotkey for logout was added for upcoming Authentic Theme 21.10 release.

By default hotkey is set to `Alt + [ + Alt + [`.
