### ISSUE TITLE
Theme Logos - Add official Webp, Webm, GIF support

### ISSUE THREAD

**Issue by shoulders** [webmin/authentic-theme#1694]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.10.0       |
|  Theme version       |     21.09.5      |
|  Package updates     |      65  package updates are available   |

## Background
Theme Configuration --> Theme Logos

![image](https://github.com/webmin/authentic-theme/assets/319997/3962580b-7b07-4ff8-bf2b-76e1b36c6bce)

## The issue
You can upload *.webp images anyway but the description says you can only use **PNG**

## Proposed Solution
Allow, officially, the use of Webp, Webm, GIF
- update the file selector to allow these file formats (I know you can use the `*.*` option)
  ![image](https://github.com/webmin/authentic-theme/assets/319997/c8ed192c-c71d-4e0f-b1ac-8109bae4a37c)
- Update the description to add these new formats because they support transparency
- enforce a MIME check on uploaded files to only allow these formats

**Why Webm?**

Just allows someone to put in an animated logo just like GIF. Allows a bit of fun but I appreciate if GIF and webm were not allow because of this.

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

All fixed in this https://github.com/webmin/authentic-theme/commit/be73964c9580cd9437050fa25022d7319c069d56 commit!
