### ISSUE TITLE
Error message appears if I try to update Authentic theme

### ISSUE THREAD

**Issue by verachell** [webmin/authentic-theme#1697]
I am running Authentic theme 21.10 on Webmin 2.111. I wanted to update authentic theme to the latest version, 21.20. So I went to Theme Configuration -> Theme Updates, then select Update Theme, then Install Latest Release Version, but then it gives an error message: 

"Installing this version of Authentic Theme 21.20 requires latest and/or possibly unreleased version of Webmin to work properly. There might be incompatible changes, that could stop the theme from working as designed. Continuing upgrade operation using UI is not possible."

But I checked my Webmin version (2.111) and it is the latest version. What should I do? Here is a screenshot in case it helps.

![Webmin_screenshot_theme_upgrade](https://github.com/user-attachments/assets/3b14797c-370f-4231-b64c-4e20c5a66421)

**Comment by iliajie** [comment]
Hello Vera!

> What should I do? Here is a screenshot in case it helps.

Absolutely nothing. Please wait for the new Webmin release.

**Comment by verachell** [comment]
Thank you! I confirm this worked perfectly. I am now on the new Webmin release 2.200 and Authentic theme 21.20.3. Everything went smoothly - Webmin prompted for the upgrades in the Webmin panel, first for Webmin and then for the Authentic theme. The updates all worked out perfectly. I confirm that the ACL's are preserved properly upon saving files. 

Thanks again for creating this wonderful admin panel. I'm so happy to have the new versions of Webmin and Authentic theme running on my server.

**Comment by iliajie** [comment]
> I confirm that the ACL's are preserved properly upon saving files.

I'm very glad to know that.

> Thanks again for creating this wonderful admin panel.

You're very welcome!

Thank you for helping to make it better!
