### ISSUE TITLE
Updates remove stats

### ISSUE THREAD

**Issue by ZimboLea** [webmin/authentic-theme#1699]
Thank you for webmin it is a wonderful tool! 
Authentic theme update  to 21.20.0 seems to break the stats history. I get the graphs but without the data lines. I went back to 21.09.5 (because that's what I had available) and it worked fine. Going up to 21.20.0 breaks it and going from there to 21.20.2 it stays broken. However when I went directly from 21.09.5 to 21.20.2 it now works fine.
I have Ubuntu server 20.04.6 running

**Comment by iliajie** [comment]
Hello,

Did you try installing latest very latest development version from Theme Configuration page?

Please give it a try and let me know if that works for you.

**Comment by iliajie** [comment]
Or trying to install latest build as described here:

https://github.com/webmin/webmin/issues/2222#issuecomment-2245177509

**Comment by shushulin76** [comment]
I can confirm this too
in webmin.errors the following things appeared at login

_**/authentic-theme/ws-572 : Websockets connection failed : Failed to connect to 127.0.0.1:572 : Connection refused**_

**Comment by shushulin76** [comment]
also the time of charts is very strange
<img width="738" alt="webmin" src="https://github.com/user-attachments/assets/e8421f58-f10a-4552-9f5e-f3d2730730b6">

**Comment by iliajie** [comment]
> also the time of charts is very strange

They are just empty.

Please give latest devel version a try and see if it works for you.

**Comment by shushulin76** [comment]
Sorry but i can't play with this server because it is important for me. I'll wait for stable version.

**Comment by ZimboLea** [comment]
As I said originally, I no longer have a problem. I solved it by going back to 21.09.5 and THEN installing the latest 21.20.2.  Nothing else worked
