### ISSUE TITLE
Stats History keeps coming back even after i hide it

### ISSUE THREAD

**Issue by Sopor** [webmin/authentic-theme#1700]
After the latest update a new stats panel have showing up on the dashboard.

I don't want it, so i have tried to hide it, but it keeps coming back.

I press on the X to the right, it disappear, but as soon as i get back to the dashboard or refresh the page it is visible again.

I have the same issue on two different computers Debian Linux 11 and Ubuntu Linux 22.04.4.

I have cleared the cache, but it won't help.

Webmin: 2.200
AT: 21.20.1
Firefox: 128
OS: Windows 10

**Comment by iliajie** [comment]
Hello,

Thanks for the heads up!

This was a bug in Webmin 2.200 but now fixed in 2.201.

By the way the real-time monitoring stats were reworked with the latest release and now perform collection much more effectively.

**Comment by Sopor** [comment]
I didn't think it was fixed so quickly, so when i couldn't find any open issue about it i created one, but then i saw there was a new version out. I should have checked the closed ones as well 😏

**Comment by iliajie** [comment]
So, it all works for you smoothly?

**Comment by Sopor** [comment]
2 out of 3 are working. The third will open `Recent Logins` every time i `Clear cache` 🙁

It has never been like that before.

**Comment by iliajie** [comment]
> The third will open `Recent Logins` every time i `Clear cache` 🙁

Can you unpack that?

**Comment by Sopor** [comment]
> Can you unpack that?

What do you mean?

**Comment by iliajie** [comment]
> What do you mean?

I just asked to elaborate.

**Comment by Sopor** [comment]
If i have the `Recent Logins` closed on the dashboard and i do a `Clear cache` it will be open (expanded or what you call it) when the dashboard is loaded again.

It has always stayed closed and it do that on two of my other computers running Webmin.

The only difference is that this computer has three entries in the `Recent Logins`.

The other two have only one.

I don't know if that will force it open after a clear cache?

Time for bed now!

**Comment by Sopor** [comment]
Here is a video:

https://github.com/user-attachments/assets/58daadda-20db-40fb-949d-b6b15ed5daeb

Should i open a new issue?

**Comment by iliajie** [comment]
Thanks for the heads up!

> Should i open a new issue?

No, because this is expected behavior.

**Comment by Sopor** [comment]
Why will it open when the other two are not doing it?

**Comment by iliajie** [comment]
Because there is a default state for each accordion. Most of them are closed by default unless opened by the server, for example, when there is something to show to the user.

However, the theme tries to remember user preference for the last open/close state, which is reset when the cache is cleared.

**Comment by Sopor** [comment]
Why will it not open on the other two dashboards?

There is nothing to see in my opinion, so i don't understand why it will open on the third one...

**Comment by iliajie** [comment]
> Why will it not open on the other two dashboards?

The reality is that the accordion's state (open/closed) has always been controlled by the server. Later, the Authentic theme played smart by remembering the user's last choice, but this memory is short and dependent on the browser.

> There is nothing to see in my opinion, so i don't understand why it will open on the third one.

Unless a problem can be described in detail with steps to reproduce the behavior, it will be difficult to provide a definite answer.

**Comment by Sopor** [comment]
It seems that it has to do with the entries in the `Recent Logins`.

When only one entry is showing it will stay close, but when there are two it will open after i clear the cache.
