### ISSUE TITLE
Extra entries - Allow beautiful JSON

### ISSUE THREAD

**Issue by shoulders** [webmin/authentic-theme#1701]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.4     |
|  Webmin version      |     2.111      |
|  Usermin version     |     2.010     |
|  Virtualmin version  |     7.20.2       |
|  Theme version       |     21.10      |
|  Package updates     |     All installed packages are up to date   |

### background

in `Theme configuratcion --> Configuration category: Naviagtion mneu --> Extra entries:` you can defined your own menus.

![image](https://github.com/user-attachments/assets/ed20515c-5476-4060-b096-0c89f820e4bc)

![image](https://github.com/user-attachments/assets/e423c433-093e-4c24-b776-57752e6ea8df)

### the issues

- `Extra entries` will not accepts beautify JSON, it has to be flattened as shown in the images above
- The tool tip shows a flattened JSON which is hard to read

### Proposed solution

- allow the use of beautiful JSON
- Update the tooltip to show a beautiful JSON

A beautiful JSON is much easier to read and manipulate

### A beautiful JSON

```json
{
  "extra": [
    {
      "title": "Google Mail",
      "link": "https://gmail.com/",
      "icon": "google",
      "level": "0,1,2,3,4"
    },
    {
      "title": "BIND DNS Server",
      "link": "/bind8",
      "icon": "server"
    },
    {
      "title": "Usermin",
      "link": "/",
      "icon": "envelope",
      "port": "20000",
      "target": "_blank"
    }
  ]
}
```

### additional

the example in the tool tip is perfect, it has the right balance of the different options you can configure

**Comment by iliajie** [comment]
Thanks for the heads up!

That is fixed now! I have also added validation for the passed data, so it won't break the theme config completely.

**Comment by shoulders** [comment]
thanks @iliajie , this is one I really wanted, I cant tell you why, but I appreciate it.

**Comment by iliajie** [comment]
You're welcome!
