### ISSUE TITLE
scrollbars interfering with usermin mailbox selection

### ISSUE THREAD

**Issue by mas-co** [webmin/authentic-theme#1703]
Hello.

I keep experiencing a minor, but annoying, issue with Usermin (v 2.102) whenever I set the window’s “Zoom” magnification to less than 100% on the “Mail” tab (where you can access the folders in the left menu) scrollbars appear. And the horizontal scrollbar at the bottom prevents clicking on the bottom-most folder. This happens with Firefox and Chrome browsers on Windows and Ubuntu.  Since it is an issue with the authentic-theme, someone suggested I post this here.

I have uploaded a screenshot, below.
![Screenshot 2024-10-11 110653](https://github.com/user-attachments/assets/1a0e7263-5378-4c9a-a211-f2789a1bbac6)

My current work-around is to flick the CTRL & mouse wheel to quickly change the browser window magnification.

Cheers!

**Comment by iliajie** [comment]
Hello,

Yes, I see this issue as well. I’ll update the ticket with progress shortly. Thanks!

**Comment by iliajie** [comment]
It took some time to find the root cause of it! I also removed the double vertical scrolling since it’s a bad UX.

**Comment by mas-co** [comment]
Fantastic!
I cannot wait until it gets rolled out with Usermin.
