### ISSUE TITLE
Pages not loading in Firefox

### ISSUE THREAD

**Issue by h9k** [webmin/authentic-theme#6]
When on the List Virtual Server page for example and clicking on a domain, the pages does not load in Firefox. The loading icon appears but nothing happens. No javascript error, no network activity in Firebug.
Chrome and IE are fine.

**Comment by h9k** [comment]
I'm afraid I need to reopen this issue. Currently running version 8.1.0.
I cannot even change the theme back to Virtualmin Framed, need to do that in another browser.

**Comment by qooob** [comment]
Have you just updated or it stopped working recently?

**Comment by qooob** [comment]
Version 9.0.0. will have complete base re-write. I bet it will work with your last-pass plugin.

Please let me know if it is, when update is ready.
