### ISSUE TITLE
Spinning Wheel - Theme Proxy Issue?

### ISSUE THREAD

**Issue by LinuxNewb27** [webmin/authentic-theme#61]
Ilia,

I seem to be having the circular loading issue again. I'm not behind my work proxy for the holidays so I had to modify settings in my virtual environment. Ubuntu Server 14.04.1. 

<b>System Proxy Settings</b>
nslookup, ping, wget, and apt-get all work...

<code>nano /etc/environment</code>

![image](https://cloud.githubusercontent.com/assets/4732566/5544427/d0ad6a92-8ac3-11e4-9311-98bcf2d7642f.png)
![image](https://cloud.githubusercontent.com/assets/4732566/5544447/518abdae-8ac4-11e4-99e3-2b4e43182803.png)
![image](https://cloud.githubusercontent.com/assets/4732566/5544450/5ef21bb8-8ac4-11e4-824f-999d0c76caa8.png)

My previous issue https://github.com/qooob/authentic-theme/issues/47 would stop at the checking version of Authentic <b>BUT</b> now it seems the script is stalled.

![image](https://cloud.githubusercontent.com/assets/4732566/5544142/b35fc710-8abd-11e4-9229-dfa011983de0.png)

If I let the script finish it looks like it takes 1 entire minute to finish or if I double right-click it, it looks like it's completed.
![image](https://cloud.githubusercontent.com/assets/4732566/5544279/917ef26c-8ac0-11e4-8cf9-8956d27f8000.png)

If I try doing a Software package Update it takes a long time to load.
![image](https://cloud.githubusercontent.com/assets/4732566/5544329/b550fe32-8ac1-11e4-9d7b-19d56366aecf.png)

I tested out my old theme and when I do a refresh on the modules it completes in a short amount of time.
![image](https://cloud.githubusercontent.com/assets/4732566/5544418/af8e24a0-8ac3-11e4-8832-04839abc18e4.png)

**Comment by LinuxNewb27** [comment]
Re-opening since I've been back in the work network. This screenshot was taken as of today. Authentic Theme comes up as 8.1.0.

There must be something behind my work firewall that is holding something up.

If I do the HTTP Tunnel for your theme version I get 9.5.0, even though the main System Information page does not detect that.

I cannot ping from my work computer or guest OS. My assumption is any kind of ICMP packets sent through the NAT are blocked. 

![image](https://cloud.githubusercontent.com/assets/4732566/6134178/9337ee6a-b11c-11e4-9fab-ab1c380d2b44.png)

**Comment by qooob** [comment]
How about now?

**Comment by LinuxNewb27** [comment]
Still shows the outdated theme without the option to download the latest.

if i double right-click when the wheel is spinning I get up to the Webmin version and then that's it. ~1-2 minutes later the rest of the info populates.

**Comment by qooob** [comment]
The problem is not on my side. Hard to tell what it is. Why don't you just download it manually from GitHub? What country you're from?

**Comment by LinuxNewb27** [comment]
As mentioned, the issue is probably caused by the router or network settings at the work office BUT it should still work properly.

I can manually update each time but the fact that my main page just sits there trying to load is more of an annoyance. 

Is there any way I can test out a DEV version that comments out the #Define remote version?

**Comment by qooob** [comment]
Open `sysinfo.cgi`: 

Find `http://rostovtsev.ru/.git/authentic-theme/VERSION.txt`

Replace with `https://raw.githubusercontent.com/qooob/authentic-theme/master/VERSION.txt`


Tell me if it helps.

P.S. What are the first 2 numbers of your IP? Like 122.122.x.x

**Comment by LinuxNewb27** [comment]
Worked like a charm. I am going to downgrade to a previous version and see what it does.

**Comment by qooob** [comment]
No, I don't have it. There is no reason for that, really. If you downloaded it from GitHub then just make sure to unpack it `authentic-theme` folder. Please tell me first two digits of your IP, I will try to see logs on the server to understand what is happening.

**Comment by LinuxNewb27** [comment]
15.227.xxx.xxx

**Comment by LinuxNewb27** [comment]
if you message me I can send that info. Since it's work IP I'd prefer not to give out that on the boards :-)

**Comment by qooob** [comment]
Are you sure it's not 115.227.xxx.xxx? Go to my webiste and email it to me.. Not sure if I could find anything though.. It seems to be the problem of your network.

**Comment by LinuxNewb27** [comment]
Sent you a personal email with more info on it.

**Comment by qooob** [comment]
you can send me the message using https://rostovtsev.ru `notifications@github.com` will not work.

**Comment by LinuxNewb27** [comment]
I did ;-)

**Comment by qooob** [comment]
Never received it, at least yet..

**Comment by LinuxNewb27** [comment]
From your website. Either way it's working now. Don't know why but it could either be in the http or https difference or a DNS issue. Proxy also introduces an issue.

![image](https://cloud.githubusercontent.com/assets/4732566/6137178/1a3e35b0-b134-11e4-8828-222f1b2bb016.png)

**Comment by qooob** [comment]
It means you sent a message already?

**Comment by qooob** [comment]
Just take my email from header and send it directly.. of `sysinfo.cgi` for example..

**Comment by LinuxNewb27** [comment]
Did. I may be MIA until tomorrow. At least the new URL works through my proxy, split tunnel, and no proxy.

Definitely interested to see where the issue may lie. In theory your URL should work too.

**Comment by qooob** [comment]
Got your email. In case it's not a new issue email me directly.
