### ISSUE TITLE
Stray </div> Tag 

### ISSUE THREAD

**Issue by itsbhanusharma** [webmin/authentic-theme#62]
I Couldn't find why does it Happens but it surely does exists on every page (Not impacting anything though) 

See the Screenshot below

![capture](https://cloud.githubusercontent.com/assets/9054382/5554130/4905ca4c-8c69-11e4-8008-b603a5811df5.PNG)

**Comment by itsbhanusharma** [comment]
Probably Not Fixed 

And Now a Stray </ul> element is also there 
![capture](https://cloud.githubusercontent.com/assets/9054382/5613290/ebd9be8a-9507-11e4-9a76-d320f2b2f522.PNG)

**Comment by qooob** [comment]
This only appears in Virtualmin, right? If so, let Joe know on Virtualmin Forums and link here please.

**Comment by itsbhanusharma** [comment]
it actually co-exists on webmin & virtualmin in my case... not sure about others... need a word from other users about it.  (preferably the GPL users) 
i'll also check other themes and if it exists i'll raise a ticket on virtualmin forum as well... gimme an hour or two to test and get final result. 
Ps.  it doesn't breaks the panel.

**Comment by qooob** [comment]
Alright, please report what you get.

**Comment by Zen4All** [comment]
> it actually co-exists on webmin & virtualmin in my case... not sure about others... need a word from other users about it. (preferably the GPL users)

I think other users do not really look in the code for stray divs :wink: , They are just using the system and as long as all works they do not care.
But I checked and see it too.
