### ISSUE TITLE
Left menu does not contain virtual server related stuff

### ISSUE THREAD

**Issue by h9k** [webmin/authentic-theme#7]
On the left menu, there are no entries for server related stuff.
Instead, those things are all on the right page, but I find the way it is in the Virtualmin Framed Theme is better because all functions are more easily accessible.
Right now, when logging in as domain user, I just see "Backup and Restore" in the left menu, all the rest is on the domain page (see attached screenshot)
![2014-10-14_20-32-31](https://cloud.githubusercontent.com/assets/1579124/4634477/ab19c462-53d0-11e4-9071-2558b32903a3.png)

**Comment by qooob** [comment]
Support for the left menu, will be added in version 9.0 for all users with Webmin 1.730+.
Thanks.
